### ISSUE TITLE
NPE when instantiating Google API Client

### ISSUE THREAD

**Issue by cdeonier** [braintree/braintree_android#102]
Hey there,

I'm currently getting this on version 2.2.1:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
        at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown:-1)
        at com.braintreepayments.api.BraintreeFragment.getGoogleApiClient(BraintreeFragment.java:512)
        at com.braintreepayments.api.BraintreeFragment$8.onConfigurationFetched(BraintreeFragment.java:505)
        at com.braintreepayments.api.BraintreeFragment$7.run(BraintreeFragment.java:454)
        at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:381)
        at com.braintreepayments.api.BraintreeFragment$5.onConfigurationFetched(BraintreeFragment.java:412)
        at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:59)
        at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:261)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I believe the issue is occurring when creating the Google API client. My guess is that because creating the Google API client is asynchronous, it's possible the Activity was destroyed and is null by the time we actually try to instantiate the Google API client via the Builder (`BraintreeFragment:512`). Unfortunately, it doesn't look like there's a way to de-register the listener for creating the Google API Client.

Let me know if I can provide further details!

**Comment by lkorth** [comment]
@cdeonier: Thanks for the report! An error will now be returned when attempting to get a `GoogleApiClient` when `BraintreeFragment` is not attached to an `Activity` instead of crashing.

This fix will go out today or tomorrow.
