### ISSUE TITLE
java.lang.IllegalStateException: Activity has been destroyed when trying to create BraintreeFragment

### ISSUE THREAD

**Issue by MiralDesai** [braintree/braintree_android#104]
I seem to be getting this crash a fair bit when trying to create a new instance of BraintreeFragment with v2 of the SDK. This is because I can initialise a new BraintreeFragment like this:

    try {
        braintreeFragment = BraintreeFragment.newInstance(context, clientToken);
    } catch (InvalidArgumentException e) {
        e.printStackTrace();
    }

but the user may have already left the activity, so when the FragmentManager returns and tries to attach the BraintreeFragment to the activity an exception is thrown, because the activity has already been destroyed. Of course this is causing my app to crash.

I assume you guys handle everything to do with the Fragment and it's transactions, so I feel like this is a bug with the SDK in that it's not properly handled. The Fragment should not be attached if the activity has been destroyed.

Let me know what you think.

**Comment by lkorth** [comment]
@MiralDesai: yes, this is something the SDK should check and handle. Do you have a stacktrace you can share?

**Comment by MiralDesai** [comment]
Yup sure can.

Here you go:

`Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1350)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
       at android.app.BackStackRecord.commit(BackStackRecord.java:705)
       at com.braintreepayments.api.BraintreeFragment.newInstance(SourceFile:128)
       at com.cakeapp.activity.AddPaymentMethod.initialiseBraintreeFragment(SourceFile:182)
       at com.cakeapp.activity.AddPaymentMethod.access$1200(SourceFile:66)
       at com.cakeapp.activity.AddPaymentMethod$GetClientToken.onPostExecute(SourceFile:652)
       at com.cakeapp.activity.AddPaymentMethod$GetClientToken.onPostExecute(SourceFile:633)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

The line is points too is the line I posted in my opening post. 

`braintreeFragment = BraintreeFragment.newInstance(context, clientToken);`

**Comment by lkorth** [comment]
@MiralDesai thanks for the report. I've added and fix, it will go out in the next release.

**Comment by MiralDesai** [comment]
Thanks, do you have a timeline for the next release? Would be handy to know so I can track it. Since I'm using 2.+ I won't know.

**Comment by lkorth** [comment]
I don't have a timeline, but it should be some time this week. We have a [Google Group](https://groups.google.com/forum/#!forum/braintree-sdk-announce) that announces releases that you can subscribe to find out when the new version comes out.

**Comment by MiralDesai** [comment]
Fantastic thanks.
