### ISSUE TITLE
App crash in Android device (Lenovo and Samsung)

### ISSUE THREAD

**Issue by bhagyasri** [braintree/braintree_android#109]
We have integrated the latest BrainTree Android SDK version 2 in our app. 
We are getting a crash in Lenovo A6000(version 4.4.4) and Samsung galaxy series(Version <=4.4). 
Could you please help us to resolve this.

Note: Also we have added the comment for this issue in Brain Tree web link too. 
Ref: https://github.com/braintree/braintree-web/issues/106

Error Log from Android device:

```
java.lang.VerifyError: com/braintreepayments/api/BraintreeFragment
at com.braintreepayments.api.BraintreePaymentActivity.getBraintreeFragment(BraintreePaymentActivity.java:298)
at com.braintreepayments.api.BraintreePaymentActivity.onCreate(BraintreePaymentActivity.java:114)
at android.app.Activity.performCreate(Activity.java:5541)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lkorth** [comment]
Which version of the SDK and Drop-in are you using? Can you include more logs before the crash? `VerifyError`s will include the issue in logcat before the crash.

**Comment by bhagyasri** [comment]
**BrainTree SDK version**: 2 
dependencies {
  compile 'com.braintreepayments.api:braintree:2.+'
  compile 'com.braintreepayments.api:drop-in:2.+'
}

**Android Mobile and OS Version:**
Lenovo - A600 (OS Version: 4.4.4)
Samsung - Galaxy (S4 mini and Grand2) (OS Version - 4.4.2) 

**ErrorLog:**
07-06 16:55:17.358 28580-28580/com.bby.uk E/dalvikvm: Could not find class 'com.google.android.gms.wallet.Cart', referenced from method com.braintreepayments.api.PaymentRequest.<init>
07-06 16:55:17.358 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to resolve const-class 4992 (Lcom/google/android/gms/wallet/Cart;) in Lcom/braintreepayments/api/PaymentRequest;
07-06 16:55:17.358 28580-28580/com.bby.uk D/dalvikvm: VFY: replacing opcode 0x1c at 0x0029
07-06 16:55:17.358 28580-28580/com.bby.uk E/dalvikvm: Could not find class 'com.google.android.gms.identity.intents.model.CountrySpecification', referenced from method com.braintreepayments.api.PaymentRequest.androidPayAllowedCountriesForShipping
07-06 16:55:17.358 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to resolve new-instance 4014 (Lcom/google/android/gms/identity/intents/model/CountrySpecification;) in Lcom/braintreepayments/api/PaymentRequest;
07-06 16:55:17.358 28580-28580/com.bby.uk D/dalvikvm: VFY: replacing opcode 0x22 at 0x000d
07-06 16:55:17.368 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/wallet/Cart;)
07-06 16:55:17.368 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/wallet/Cart;)
07-06 16:55:17.388 28580-28580/com.bby.uk E/dalvikvm: Could not find class 'com.google.android.gms.wallet.Cart', referenced from method com.braintreepayments.api.PaymentRequest.writeToParcel
07-06 16:55:17.388 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to resolve const-class 4992 (Lcom/google/android/gms/wallet/Cart;) in Lcom/braintreepayments/api/PaymentRequest;
07-06 16:55:17.388 28580-28580/com.bby.uk D/dalvikvm: VFY: replacing opcode 0x1c at 0x0014
07-06 16:55:17.388 28580-28580/com.bby.uk I/dalvikvm: DexOpt: unable to optimize static field ref 0x40a3 at 0x51 in Lcom/braintreepayments/api/PaymentRequest;.<init>
07-06 16:55:17.388 28580-28580/com.bby.uk D/dalvikvm: DexOpt: unable to opt direct call 0x6f5f at 0x0f in Lcom/braintreepayments/api/PaymentRequest;.androidPayAllowedCountriesForShipping
07-06 16:55:17.388 28580-28580/com.bby.uk I/Timeline: Timeline: Activity_launch_request id:com.bby.uk time:332387019
07-06 16:55:17.408 28580-28580/com.bby.uk V/BBWalletRechargeFragment: onPause()
07-06 16:55:17.418 28580-28580/com.bby.uk V/BBProfileFragmentContainer: onPause()
07-06 16:55:17.418 28580-28580/com.bby.uk V/BBMainActivity: onPause()
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to resolve static field 19420 (API) in Lcom/google/android/gms/wallet/Wallet;
07-06 16:55:17.478 28580-28580/com.bby.uk D/dalvikvm: VFY: replacing opcode 0x62 at 0x001f
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: DexOpt: method is in an interface
07-06 16:55:17.478 28580-28580/com.bby.uk I/dalvikvm: Could not find method com.google.android.gms.common.api.GoogleApiClient.isConnected, referenced from method com.braintreepayments.api.BraintreeFragment.getGoogleApiClient
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: VFY: unable to resolve virtual method 26449: Lcom/google/android/gms/common/api/GoogleApiClient;.isConnected ()Z
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: VFY:  rejecting opcode 0x6e at 0x004b
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: VFY:  rejected Lcom/braintreepayments/api/BraintreeFragment;.getGoogleApiClient ()Lcom/google/android/gms/common/api/GoogleApiClient;
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: Verifier rejected class Lcom/braintreepayments/api/BraintreeFragment;
07-06 16:55:17.478 28580-28580/com.bby.uk D/AndroidRuntime: Shutting down VM
07-06 16:55:17.478 28580-28580/com.bby.uk W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415ccd58)
07-06 16:55:22.668 28580-28624/com.bby.uk E/GAv4: Successfully bound to service but never got onServiceConnected callback
07-06 16:55:22.698 28580-28580/com.bby.uk E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: com.bby.uk, PID: 28580
                                                            java.lang.VerifyError: com/braintreepayments/api/BraintreeFragment
                                                                at com.braintreepayments.api.BraintreePaymentActivity.getBraintreeFragment(BraintreePaymentActivity.java:298)
                                                                at com.braintreepayments.api.BraintreePaymentActivity.onCreate(BraintreePaymentActivity.java:114)
                                                                at android.app.Activity.performCreate(Activity.java:5231)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
                                                                at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by lkorth** [comment]
Does your app depend on Google Play Services or any subset of Google Play Services?

**Comment by bhagyasri** [comment]
Yes, We have used three services related to Google Play Services.

compile 'com.google.android.gms:play-services-maps:7.5.0'
compile 'com.google.android.gms:play-services-analytics:7.5.0'
compile 'com.google.android.gms:play-services-location:7.5.0'

**Comment by lkorth** [comment]
The [SDK requires Google Play Services >= 8.4.0 and < 9.0.0](https://github.com/braintree/braintree_android/blob/4e5c024e21633a87552d52be8f973a80760a11c0/Braintree/build.gradle#L33). In Google Play Services 8.0.0 the `GoogleApiClient` changed from an abstract class to an interface which is causing this verify error. You'll need to compile against at least Google Play Services 8.0.0 to fix this error.

**Comment by bhagyasri** [comment]
I have updated Google play services and the issue is solved. Thanks for you help.
