### ISSUE TITLE
I got java.lang.NullPointerException in Firebase Crashletics.

### ISSUE THREAD

**Issue by arjunsvd** [braintree/braintree_android#1146]
I got java.lang.NullPointerException in Firebase Crashletics.
sdk version: com.braintreepayments.api:drop-in:6.16.0
play-services-wallet version: com.google.android.gms:play-services-wallet:19.4.0

Fatal Exception: java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.app.inmatephotos/com.braintreepayments.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
       at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124)
       at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78)
       at android.app.Activity.performCreate(Activity.java:8050)
       at android.app.Activity.performCreate(Activity.java:8030)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
        
        Effected Device & OS version listed below:-
        1) Sdk_gphone_arm64 OS 11
        2) Pixel 6  OS 12
        3) GCE X86 Phone OS 9
        4) TCL 30 Z OS 12

_Originally posted by @arjunsvd in https://github.com/braintree/braintree-android-drop-in/issues/404#issuecomment-2337253759_

**Comment by jaxdesmarais** [comment]
Closing this issue due to inactivity and age - please open a new issue if this is ongoing on the latest version (v5) of the SDK.
