### ISSUE TITLE
java.net.MalformedURLException

### ISSUE THREAD

**Issue by gregmcgowan** [braintree/braintree_android#117]
We have found an issue with the latest SDK (2.3.6) that we can reproduce reliably.

The issue occurs when we in our payment activity which contains a button that allows the user to pay using pay pal ( calling PayPal.requestOneTimePayment) 

This payment activity requests a token from our server. Once that is obtained we intialise the BrainTreet  fragment with  BraintreeFragment.newInstance() 

Once the activity is started with the token, then we put the app into the background and kill the process (using the terminate process button in Android studio) and then go back into the app and then attempt to make paypal payment we get the following exception 
 

`                                                                               Protocol not found: null/v1/paypal_hermes/create_payment_resource
                                                                                 java.net.MalformedURLException: Protocol not found: null/v1/paypal_hermes/create_payment_resource
                                                                                     at java.net.URL.<init>(URL.java:176)
                                                                                     at java.net.URL.<init>(URL.java:125)
                                                                                     at com.braintreepayments.api.internal.HttpClient.init(HttpClient.java:226)
                                                                                     at com.braintreepayments.api.internal.BraintreeHttpClient.init(BraintreeHttpClient.java:126)
                                                                                     at com.braintreepayments.api.internal.HttpClient.post(HttpClient.java:209)
                                                                                     at com.braintreepayments.api.internal.BraintreeHttpClient.post(BraintreeHttpClient.java:121)
                                                                                     at com.braintreepayments.api.internal.HttpClient$2.run(HttpClient.java:185)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
`

We can provide more information if you need

**Comment by lkorth** [comment]
This was fixed in 1907afe793e645b4959efe877222b2c7af2759d0 and will go out in the next release.

**Comment by gregmcgowan** [comment]
Any idea when the next release will be?

**Comment by lkorth** [comment]
Today or tomorrow.
