### ISSUE TITLE
Android Pay fails with Request Failed: unexpected error

### ISSUE THREAD

**Issue by hussainak** [braintree/braintree_android#119]
Hi there,

I am starting Braintree Android v2 Drop In using the following code with a production client roken generated on my nodejs server application. PayPal and CC work fine but I am getting an error when tapping on Android Pay. Error is included below the code. Please help me here!

```java
Cart cart = Cart.newBuilder()
            .setCurrencyCode("USD")
            .setTotalPrice("1.00")
            .addLineItem(LineItem.newBuilder()
                    .setCurrencyCode("USD")
                    .setDescription("Description")
                    .setQuantity("1")
                    .setUnitPrice("1.00")
                    .setTotalPrice("1.00")
                    .build())
            .build();

      PaymentRequest paymentRequest = new PaymentRequest()
                .clientToken(clientToken)
                .actionBarTitle("Test")
                .primaryDescription("Test desc")
                .secondaryDescription("1 Item")
                .amount("$1.00")
                .submitButtonText("Give Now");
        paymentRequest.androidPayCart(cart);
        paymentRequest.androidPayRequestCode(MASKED_WALLET_REQUEST_CODE);

     startActivityForResult(this, paymentRequest.getIntent(getActivity()), DROPIN_ACTIVITY_REQUEST_CODE);
```

The Eror that comes up on the screen is "Request Failed", "An unexpected  error has occurred. Please try again later".

I am getting the following logcat when the error occurs.

```
09-13 00:49:40.802 3499-4137/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.wallet.shared.BuyFlowConfig
                                         java.lang.ClassNotFoundException: com.google.android.gms.wallet.shared.BuyFlowConfig
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6195)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161)
                                             at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6855)
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310)
                                             at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6613)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.google.android.gms.wallet.shared.BuyFlowConfig
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6195) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161) 
                                             at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6855) 
                                             at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310) 
                                             at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6613) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by lkorth** [comment]
[The SDK requires Google Play Services Wallet 9.0.0 or higher](https://github.com/braintree/braintree_android/blob/master/Braintree/build.gradle#L33). Which version is your app using? This crash is typically caused by a major version mismatch since the SDK is compiled against 9.x and the code it expects may not be there if you're including a different major version.

**Comment by hussainak** [comment]
My gradle depedencies are:

```
compile "com.android.support:support-v4:+"
    compile "com.android.support:support-v13:23+"
    compile "com.google.android.gms:play-services-gcm:+"
    compile "com.braintreepayments.api:braintree:2.+"
    compile "com.braintreepayments.api:drop-in:2.+"
    compile "com.google.android.gms:play-services-wallet:+"
```

**Comment by lkorth** [comment]
Which versions of those libraries are actually being used? If you look in your app's `build/intermediates/exploded-aar` directory you should be able to see which version is being used to compile.

**Comment by hussainak** [comment]
I have 9.0.2 and 9.2.1 for play-services-gcm and same ones for wallet. Thanks for helping out :)

**Comment by lkorth** [comment]
The current version of the Braintree SDK is compiled against 9.4.0. I would recommend trying that version first. It looks like there may have been some changes between 9.0.0 and 9.4.0 that are causing these unmarshalling errors.

**Comment by hussainak** [comment]
I have updated both libraries to use 9.4.0 but still have the same error

**Comment by lkorth** [comment]
Do you have a simple app that reproduces this issue so we can investigate further?

**Comment by hussainak** [comment]
The sample client token from braintree does not bring up android pay button, but essentially thats all the code I have that I have posted above. The only difference is the client token is being fetched from my nodejs server. Fetching the client token requires authentication to the api I developed. 
Would this help you ?

**Comment by hussainak** [comment]
[BTTest.zip](https://github.com/braintree/braintree_android/files/471286/BTTest.zip)

**Comment by lkorth** [comment]
The `ClassNotFound` was just log noise. You're missing a key declaration in your Android Manifest. The log line output after the error:

```
W WalletMerchantError: Error in loadMaskedWallet: To use this API, you must add the following tag to your manifest: <meta-data android:name="com.
google.android.gms.wallet.api.enabled" android:value="true" />
```

After adding it to the manifest I was able to use Android Pay in your sample app.

Please see [the first code snippet in the docs](https://developers.braintreepayments.com/guides/android-pay/client-side/android/v2) after including the dependency for Android Pay or [the Android Pay setup docs](https://developers.google.com/android-pay/setup)

**Comment by hussainak** [comment]
Thanks Luke, it was a copy paste error I am actually not missing the meta-data tag in my original app. When I include this in the test app I am still getting the same error. AndroidManifest below:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="companyname.com.bttest">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
    </application>

</manifest>`

**Comment by lkorth** [comment]
Adding the `meta-data` tag allows me to successfully complete Android Pay in your sample app. You may want to test it on other devices or check the version of Google Play Services installed on your device.

**Comment by hussainak** [comment]
After looking a little more I found the following error:
W/WalletMerchantError: Error in loadMaskedWallet: You have not registered to use this API.
I am not sure if this is covered by the docs.

**Comment by lkorth** [comment]
Are you testing this in production?

It's not possible to use Android Pay in production until [after your app has been reviewed and enabled by Google.](https://developers.braintreepayments.com/guides/android-pay/testing-go-live#go-live)

**Comment by hussainak** [comment]
Yes this is in production. Thanks Luke that clarifies!
