### ISSUE TITLE
Cardinal DiskReadViolation

### ISSUE THREAD

**Issue by DBroli** [braintree/braintree_android#1208]
### Braintree SDK Version

4.49.1

### Environment

Sandbox

### Android Version & Device

Emulator - Android 10.0

### Braintree dependencies

"com.braintreepayments.api", name = "card", version.ref = "4.49.1" 
"com.braintreepayments.api", name = "paypal", version.ref = "4.49.1" 
"com.braintreepayments.api", name = "google-pay", version.ref = "4.49.1" 
"com.braintreepayments.api", name = "three-d-secure", version.ref = "4.49.1" 

### Describe the bug

A UI test has failed with a DiskReadViolation. Judging by the stacktrace, this seems to be in issue in Cardinal SDK.

`java.lang.Error: android.os.strictmode.DiskReadViolation
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
at java.io.File.exists(File.java:815)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
at android.app.ContextImpl.getFilesDir(ContextImpl.java:681)
at android.app.ContextImpl.openFileInput(ContextImpl.java:599)
at android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
at com.cardinalcommerce.a.setOutlineAmbientShadowColor.configure(SourceFile:25)
at com.cardinalcommerce.a.setTranslationY.configure(SourceFile:143)
at com.cardinalcommerce.a.setTranslationY.getInstance(SourceFile:85)
at com.cardinalcommerce.a.setTranslationY.configure(SourceFile:125)
at com.cardinalcommerce.a.setTranslationY.configure(SourceFile:119)
at com.cardinalcommerce.a.setTranslationY.cca_continue(SourceFile:47)
at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView.onCreate(SourceFile:141)
at android.app.Activity.performCreate(Activity.java:7802)
at android.app.Activity.performCreate(Activity.java:7791)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:766)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:107)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:156)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:510)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:433)
at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:250)
at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:175)
at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:138)
at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:168)
at androidx.test.espresso.action.Tap.access$100(Tap.java:30)
at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:46)
at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:134)
`

### To reproduce

1. Perform a payment with a card, get a ThreeDSecure challenge
2. Attempt to complete the challenge
3. When the test was attempting to insert the text in the box, the crash has occured.

### Expected behavior

The challenge is completed succesfully without StrictMode violations.

**Comment by sarahkoop** [comment]
Hi @DBroli - We have reached out to the Cardinal team about this issue and will report here when we have an update!

**Comment by sarahkoop** [comment]
We received the following update from the Cardinal team about this:
```
CardinalMobileSDK uses custom views as per PCI and Visa Security recommendations(specs).

The ability to perform Automated UI test will be unavailable for the SDK Challenge screens for this reason. This is not something we are able to change nor make available.
```

Closing this issue out since this can't be changed.

**Comment by DBroli** [comment]
@sarahkoop 
Hello, this seems to be reproducible even outside of testing. This problem still occurs when StrictMode is enabled.
