### ISSUE TITLE
Drop-in Payment UI onActivityResult returning 0

### ISSUE THREAD

**Issue by f0restgump92** [braintree/braintree_android#122]
Hi guys, i'm facing a strange issue with Drop-in 
On debug build when i try to create payment request nothing happens, onActivityResult is immediately called with result = 0, with no stacktrace.

On release build it says it cannot find PaymentRequest.class.

this is my settup gradle

```groovy
compile 'com.braintreepayments.api:braintree:2+'
compile 'com.braintreepayments.api:drop-in:2.+'
``` 

Purchase Activity

//im getting valid clientToken from the backend
```java
PaymentRequest paymentRequest = new PaymentRequest()
                .clientToken(clientToken.getClientToken())
                .amount(selectedDeal.getPrice())
                .actionBarLogo(R.mipmap.icon_logo_register)
                .actionBarTitle(getString(R.string.titile))
                .secondaryDescription(String.valueOf(selectedDeal.geCoins()))
                .primaryDescription("Get your Coins")
                .submitButtonText("Pay");

  startActivityForResult(paymentRequest.getIntent(this), REQUEST_CODE);
```

Proguard

`-keep class com.braintreepayments.** { *; }`

**Comment by lkorth** [comment]
Please note: Drop-In is now located in a [new repo](https://github.com/braintree/braintree-android-drop-in).
 
`0` is [`Activity#RESULT_CANCELED`](https://developer.android.com/reference/android/app/Activity.html#RESULT_CANCELED). The only time `RESULT_CANCELED` is returned from Drop-In is when back or up is pressed. Is there anything else contained within the `Intent` that comes back in `Activity#onActivityResult`? Do you have a build of your app or a simple app that demonstrates this behavior?

There should be no need for special ProGuard statements with the SDK, the SDK [already contains](https://github.com/braintree/braintree_android/blob/50158ec70dc71f9bd4661b6572c7cabf1abe6e6c/Braintree/proguard-rules.cfg) a ProGuard file that handles the libraries it uses.

**Comment by f0restgump92** [comment]
We are preparing the app for production, so i still don't have anything to share
Data returned from onResult is null, no additional info.

Iw tried the new repo. and im facing the same bahaviour, when i get the token nothing happens. Start activity for result is called with no data.

changed the part of making request to 

`  DropInRequest dropInRequest = new DropInRequest()
                .clientToken(clientToken.getClientToken());
        startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE);`

**Comment by f0restgump92** [comment]
No, im not seeing anything in the logcat. 

Just this warning:
` Verification of void com.braintreepayments.api.dropin.DropInRequest.<init>(android.os.Parcel) took 277.838ms
`

**Comment by f0restgump92** [comment]
Note that on release build i'm getting this:

This is why i thought that this was proguard error

`Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest
                                           java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.Class.forName(Class.java:324)
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                               at android.os.Parcel.readParcelable(Parcel.java:2358)
                                               at android.os.Parcel.readValue(Parcel.java:2264)
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                               at android.os.BaseBundle.getString(BaseBundle.java:920)
                                               at android.content.Intent.getStringExtra(Intent.java:6195)
                                               at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699)
                                               at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161)
                                               at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6326)
                                               at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6104)
                                               at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
                                               at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990)
                                               at android.os.Binder.execTransact(Binder.java:453)
                                            Caused by: java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:324) 
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                               at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                               at android.os.Parcel.readValue(Parcel.java:2264) 
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                               at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                               at android.content.Intent.getStringExtra(Intent.java:6195) 
                                               at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2699) 
                                               at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2161) 
                                               at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6326) 
                                               at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6104) 
                                               at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170) 
                                               at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3990) 
                                               at android.os.Binder.execTransact(Binder.java:453) 
                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by lkorth** [comment]
Unfortunately without more information or a setup that can reproduce the issue, there's nothing we can investigate around why Drop-In is canceling as soon as it's launched. You may want to try an integration using `BraintreeFragment` just to see if you get any errors back after you create the fragment in an error listener. You could also try using your client token in the Demo app in this repo to see if any errors occur there.

There may be an issue with your ProGuard configuration then, but that is more of a separate issue. If you are referencing `DropInRequest` in your code there's no reason that ProGuard should remove that class.

**Comment by f0restgump92** [comment]
Thank you for your fast reply, Il try to set up with fragment and get back to you shortly

**Comment by f0restgump92** [comment]
Ok, you may close this issue. Im using Rx extension for Retforit so the exception was thrown and handled by Observable `onError` method, so that was the reason why i coulnd't see anything in the logs. 

When i moved `PaymentRequest` to the `onCreate` of my activity, stackTrace was clear. and it was saying that it cannot find `BraintreePaymentActivity`.

Iw added your activity to the `manifest` and everything is working like a charm.

Again, thank you help

**Comment by lkorth** [comment]
@f0restgump92: if you are including the dependency with Gradle, the manifest from the SDK should be automatically merged with yours and there should be no need to add the `Activity` manually.

**Comment by f0restgump92** [comment]
Yeah i know, it maybe something with `manifest merger`
This might be the issue
Im using `tools:node="replace"` in my Manifest root tag, but that should be applied only for conflicts, should add activity non the less

**Comment by jamesdixon** [comment]
@f0restgump92 did you ever figure this out? Running into it when building with the cordova-plugin-braintree plugin.
