### ISSUE TITLE
NullPointerException when trying to get new instance of BraintreeFragment

### ISSUE THREAD

**Issue by MiralDesai** [braintree/braintree_android#125]
A crash being reported to me:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler android.app.FragmentHostCallback.getHandler()' on a null object reference`

Full stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler android.app.FragmentHostCallback.getHandler()' on a null object reference
       at android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1530)
       at android.app.BackStackRecord.commitNow(BackStackRecord.java:681)
       at com.braintreepayments.api.BraintreeFragment.newInstance(SourceFile:157)
       at com.app.activity.AddPaymentMethod.initialiseBraintreeFragment(SourceFile:185)
       at com.app.activity.AddPaymentMethod.access$1200(SourceFile:66)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Not happening on my side since this is all within one method (initialiseBraintreeFragment()) which is setup exactly as the braintree docs suggest.

Could you guys look into this? Thanks. v2.3.10 of the Braintree SDK

**Comment by lkorth** [comment]
This is on API 24 or above correct? Can you confirm if this is being run on that main thread or a background thread?

**Comment by MiralDesai** [comment]
API 24 correct. It's being run on the main thread.

**Comment by MiralDesai** [comment]
Any updates on this?

**Comment by lkorth** [comment]
@MiralDesai: it doesn't look like there is a fix for this, only a work around. We're reviewing the work around and will push it soon.

**Comment by MiralDesai** [comment]
Fair enough.

**Comment by lkorth** [comment]
Thanks for the report, the fix will go out in the next release.

**Comment by jackabe** [comment]
How did you manage to fix this?

Thanks..
