### ISSUE TITLE
find this bug when run demo 

### ISSUE THREAD

**Issue by 389273716** [braintree/braintree_android#127]
```
11-08 17:24:24.979 11347-11356/com.braintreepayments.demo E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                        java.lang.Throwable: Explicit termination method 'close' not called
                                                                            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                            at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:179)
                                                                            at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:905)
                                                                            at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:897)
                                                                            at android.view.IAssetAtlas$Stub$Proxy.getProgramFd(IAssetAtlas.java:223)
                                                                            at android.view.HardwareRenderer$Gl20Renderer.initAtlas(HardwareRenderer.java:2071)
                                                                            at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:1128)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1984)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6466)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5328)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lkorth** [comment]
There isn't anything useful in that stacktrace. Do you have any more logs around when it happened or what action was performed that caused this?

**Comment by 389273716** [comment]
When I run the demo , the bug happened. Crashed in MainActivity after I saw MainActivity view.Normal operation of the demo on the Nexus,but crashed on Ibiza_F2 (Android 4.4.4 API19)
other logs show:

11-09 09:37:51.440 10398-10398/com.braintreepayments.demo E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
11-09 09:37:51.498 10398-10398/com.braintreepayments.demo E/dalvikvm: Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
11-09 09:37:51.596 916-950/? E/libPerfService: Could not open '/proc/hps/num_base_perf_serv'
11-09 09:37:51.596 916-950/? E/libPerfService: error : 13, Permission denied
11-09 09:37:51.596 916-950/? E/libPerfService: Could not open '/proc/cpufreq/cpufreq_limited_by_hevc'
11-09 09:37:51.596 916-950/? E/libPerfService: error : 13, Permission denied
11-09 09:37:52.234 10398-10416/com.braintreepayments.demo E/NativeCrypto: ssl=0x67af04b0 cert_verify_callback x509_store_ctx=0x669f6660 arg=0x0
11-09 09:37:52.234 10398-10416/com.braintreepayments.demo E/NativeCrypto: ssl=0x67af04b0 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
11-09 09:37:52.239 10398-10419/com.braintreepayments.demo E/NativeCrypto: ssl=0x67c80178 cert_verify_callback x509_store_ctx=0x66c3c5c0 arg=0x0
11-09 09:37:52.239 10398-10419/com.braintreepayments.demo E/NativeCrypto: ssl=0x67c80178 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA

**Comment by lkorth** [comment]
Those logs do not show anything useful either. There's usually more information before and after the stacktrace that typically points to the issue. Also note that while this is not ideal, this isn't really a bug, the demo app has strict mode enabled to watch for missing `close` calls, file access or networking on the main thread, ect and this may be in a library used in the demo app.

**Comment by sdcoffey** [comment]
@389273716 It's been awhile since there's been any activity on this issue, so I'm going to close it for now. Please let us know if it comes up again.
