### ISSUE TITLE
java.lang.SecurityException: new SecureRandom()

### ISSUE THREAD

**Issue by hubertSwiecioch** [braintree/braintree_android#151]
### General information

* SDK/Library version: 2.4.2
* Environment: Sandbox/Production
* Android Version and Device: 4.3/ 4.2.2

### Issue description

``` 
Caused by: java.lang.SecurityException: new SecureRandom() backed by wrong Provider: class com.tozny.crypto.android.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandomProvider
                                                     at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:115)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply(PRNGFixes.java:46)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>(EncryptionUtils.java:19)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39) 
                                                     at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73) 
                                                     at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:562) 
                                                     at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146) 
                                                     at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681) 
                                                     at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:615) 
                                                     at com.braintreepayments.api.BraintreeFragment$9.onConfigurationFetched(BraintreeFragment.java:641) 
                                                     at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:68) 
                                                     at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:286) 
```

**Comment by lkorth** [comment]
Are you also using [java-aes-crypto](https://github.com/tozny/java-aes-crypto)? There is a narrow race condition when multiple code paths attempt to set up PRNG fixes. See tozny/java-aes-crypto#11 for more details. The latest version of java-aes-crypto should synchronize correctly and prevent this issue, but if it is still occurring we could relax the check in PRNG fixes to prevent this crash.

**Comment by hubertSwiecioch** [comment]
I changed the library, but the problem remains the same:

com.facebook.android.crypto.keychain.SecureRandomFix$LinuxPRNGSecureRandomProvider
                                                     at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:115)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply(PRNGFixes.java:46)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>(EncryptionUtils.java:19)
                                                     at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39) 
                                                     at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73) 
                                                     at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:562) 
                                                     at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146) 
                                                     at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681) 
                                                     at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:615) 
                                                     at com.braintreepayments.api.BraintreeFragment$9.onConfigurationFetched(BraintreeFragment.java:641) 
                                                     at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:68) 
                                                     at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:286)

**Comment by GrzegorzFeather** [comment]
Hi, I'm experiencing same issue with my app in Android 4.3, sdk version is 2.5.2:

```
new SecureRandom() backed by wrong Provider: class com.exacttarget.etpushsdk.util.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandomProvider
	at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom()(PRNGFixes.java:115)
	at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply()(PRNGFixes.java:46)
	at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>()(EncryptionUtils.java:19)
	at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey()(OtcCrypto.java:39)
	at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>()(AuthorizationRequest.java:73)
	at com.braintreepayments.api.PayPal.getAuthorizationRequest()(PayPal.java:562)
	at com.braintreepayments.api.PayPal$1.onConfigurationFetched()(PayPal.java:146)
	at com.braintreepayments.api.BraintreeFragment$11.run()(BraintreeFragment.java:681)
	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback()(BraintreeFragment.java:605)
	at com.braintreepayments.api.BraintreeFragment.waitForConfiguration()(BraintreeFragment.java:673)
	at com.braintreepayments.api.PayPal.authorizeAccount()(PayPal.java:121)
	at com.braintreepayments.api.PayPal.authorizeAccount()(PayPal.java:108)
```

**Comment by lkorth** [comment]
I just released a snapshot (`2.5.4-SNAPSHOT`) that synchronizes on `java.security.Security.class` to try and prevent these crashes. Please give it a try and let us know if that fixes the crash.

**Comment by hubertSwiecioch** [comment]
During the first tests I did not find the previous problem. If problem reproduces in further tests it will post here.

**Comment by GrzegorzFeather** [comment]
@lkorth Having different crash now:
```
06-26 05:46:12.243 5476-5476/com.stubhub E/AndroidRuntime: FATAL EXCEPTION: main
                                                           java.lang.ExceptionInInitializerError
                                                               at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39)
                                                               at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73)
                                                               at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569)
                                                               at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146)
                                                               at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681)
                                                               at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605)
                                                               at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673)
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121)
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108)
```

**Comment by lkorth** [comment]
@GrzegorzFeather the `ExceptionInInitializerError` indicates that there is an exception in a static initializer (currently where we apply the PRNG fixes). That is with `2.5.4-SNAPSHOT`? Is there any other stacktrace higher up in the log that could indicate the actual error that is happening?

**Comment by GrzegorzFeather** [comment]
This is the full stack trace:
```
06-26 08:04:40.108 23672-23672/com.xxxxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                             java.lang.ExceptionInInitializerError
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39)
                                                                 at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73)
                                                                 at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569)
                                                                 at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146)
                                                                 at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681)
                                                                 at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605)
                                                                 at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673)
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121)
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108)
                                                                 at com.xxxxxxxxx.payments.PaymentsActivity$5.onBTClientTokenReceived(PaymentsActivity.java:247)
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils.notifyBTClientTokenReceived(PaymentsUtils.java:141)
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils.access$000(PaymentsUtils.java:52)
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils$1.onSuccess(PaymentsUtils.java:128)
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils$1.onSuccess(PaymentsUtils.java:125)
                                                                 at com.xxxxxxxxx.network.retrofit.SHNetworkManager$4.run(SHNetworkManager.java:116)
                                                                 at android.os.Handler.handleCallback(Handler.java:730)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.lang.SecurityException: new SecureRandom() backed by wrong Provider: class com.exacttarget.etpushsdk.util.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandomProvider
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:121)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply(PRNGFixes.java:46)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>(EncryptionUtils.java:19)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39) 
                                                                 at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73) 
                                                                 at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569) 
                                                                 at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146) 
                                                                 at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681) 
                                                                 at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605) 
                                                                 at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673) 
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121) 
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108) 
                                                                 at com.xxxxxxxxx.payments.PaymentsActivity$5.onBTClientTokenReceived(PaymentsActivity.java:247) 
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils.notifyBTClientTokenReceived(PaymentsUtils.java:141) 
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils.access$000(PaymentsUtils.java:52) 
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils$1.onSuccess(PaymentsUtils.java:128) 
                                                                 at com.xxxxxxxxx.payments.utils.PaymentsUtils$1.onSuccess(PaymentsUtils.java:125) 
                                                                 at com.xxxxxxxxx.network.retrofit.SHNetworkManager$4.run(SHNetworkManager.java:116) 
                                                                 at android.os.Handler.handleCallback(Handler.java:730) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by lkorth** [comment]
@GrzegorzFeather the crash you posted has the same root issue, it just happens to be wrapped in the `ExceptionInInitializerError`. Please try the `2.5.4-SNAPSHOT`, it contains a fix that should hopefully fix the crash. @hubertSwiecioch already mentioned that it fixed it for them in the first round of testing.

**Comment by GrzegorzFeather** [comment]
@lkorth using 2.5.4-SNAPSHOT did not fix the issue for me, I get same stacktrace I posted in my previous comment:

<img width="229" alt="screen shot 2017-06-28 at 11 10 56 am" src="https://user-images.githubusercontent.com/3044632/27652986-8665da5c-5bf2-11e7-8d8a-c1e54772f3c7.png">

```
06-28 06:02:10.635 13683-13683/com.xxxxxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                             java.lang.ExceptionInInitializerError
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39)
                                                                 at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73)
                                                                 at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569)
                                                                 at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146)
                                                                 at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681)
                                                                 at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605)
                                                                 at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673)
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121)
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108)
Caused by: java.lang.SecurityException: new SecureRandom() backed by wrong Provider: class com.exacttarget.etpushsdk.util.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandomProvider
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:121)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply(PRNGFixes.java:46)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>(EncryptionUtils.java:19)
                                                                 at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39) 
                                                                 at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73) 
                                                                 at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569) 
                                                                 at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146) 
                                                                 at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681) 
                                                                 at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605) 
                                                                 at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673) 
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121) 
                                                                 at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108) 
```

**Comment by lkorth** [comment]
@GrzegorzFeather thanks for testing `2.5.4-SNAPSHOT`. I was finally able to reproduce the issue and have made another fix for the crash. Please try `2.5.5-SNAPSHOT` and let us know if it fixes your crash.

**Comment by GrzegorzFeather** [comment]
Hi @lkorth it is still crashing for me on a clean build :/ If this serves any help, I also have the data-collector dependency in my project:

<img width="274" alt="screen shot 2017-06-29 at 11 08 18 am" src="https://user-images.githubusercontent.com/3044632/27703190-717b5120-5cbb-11e7-9461-39fba7f63af2.png">

```
06-29 14:07:18.930 3081-3081/com.xxxxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                           java.lang.ExceptionInInitializerError
                                                               at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39)
                                                               at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73)
                                                               at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569)
                                                               at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146)
                                                               at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681)
                                                               at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605)
                                                               at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673)
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121)
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108)
                                                            Caused by: java.lang.SecurityException: new SecureRandom() backed by wrong Provider: class com.exacttarget.etpushsdk.util.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandomProvider
                                                               at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:121)
                                                               at com.paypal.android.sdk.onetouch.core.encryption.PRNGFixes.apply(PRNGFixes.java:46)
                                                               at com.paypal.android.sdk.onetouch.core.encryption.EncryptionUtils.<clinit>(EncryptionUtils.java:19)
                                                               at com.paypal.android.sdk.onetouch.core.encryption.OtcCrypto.generateRandom256BitKey(OtcCrypto.java:39) 
                                                               at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.<init>(AuthorizationRequest.java:73) 
                                                               at com.braintreepayments.api.PayPal.getAuthorizationRequest(PayPal.java:569) 
                                                               at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:146) 
                                                               at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681) 
                                                               at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:605) 
                                                               at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:673) 
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:121) 
                                                               at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:108) 
```

**Comment by crookedneighbor** [comment]
@GrzegorzFeather are you still experiencing issues with the latest version of the SDK?
