### ISSUE TITLE
ConcurrentModificationException in BraintreeFragment

### ISSUE THREAD

**Issue by rsavin** [braintree/braintree_android#152]
### General information

* Library version: 2.5.1
* Environment: Production
* Android Version and Device: 
Devices: Samsung Galaxy S6/7 Edge; Nexus 5X
OS: 6.0.1, 7.1.2

### Issue description

We do the following: 
```
BraintreeFragment braintreeFragment = BraintreeFragment.newInstance(getActivity(), token);
return DataCollector.collectDeviceData(braintreeFragment, MERCHANT_ID);
```
After updating Braintree's version from 2.3.0 to 2.5.1 we started receive the crash:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:624)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
       at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:605)
       at com.braintreepayments.api.BraintreeFragment.onResume(BraintreeFragment.java:232)
       at android.app.Fragment.performResume(Fragment.java:2399)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
       at android.app.BackStackRecord.run(BackStackRecord.java:816)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

It happens on production and we don't have steps to reproduce.

**Comment by sdcoffey** [comment]
Hey @rsavin, 

Thanks for opening this issue. I'm not able to reproduce the unforch, are you calling `BraintreeFragment.newInstance` on the main thread?

Also note that since 2.3.0, we've deprecated `DataCollector.collectData(BraintreeFragment, String)`. I would recommend trying its replacement, `DataCollector.collectDeviceData(BraintreeFragment, String, BraintreeResponseListener)`. Let me know if that's an acceptable solution and fixes your issue, which will give us a better indication of where the issue might be.

**Comment by rsavin** [comment]
Hi @sdcoffey, thanks for the answer.

> are you calling BraintreeFragment.newInstance on the main thread

No, we do it in a worker thread. 

I'll try to use the method with `BraintreeResponseListener` and will write if it doesn't help. But it'll take a while because we can't reproduce it and we need to wait for data from production.

**Comment by sdcoffey** [comment]
Great! Let us know how that works.

I would also recommend not calling `newInstance` from a background thread. Internally, we call [`FragmentManager.executePendingTransactions`](https://github.com/braintree/braintree_android/blob/master/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L146) after adding `BraintreeFragment` to your activity's Fragment stack. The docs for [`executePendingTransactions`](https://developer.android.com/reference/android/app/FragmentManager.html) are pretty clear that this method should only be called from the main thread.

**Comment by sdcoffey** [comment]
Closing this due to inactivity. Please open a new issue if the problem remains. Thanks!
