### ISSUE TITLE
SQLiteCantOpenDatabaseException crashes the app

### ISSUE THREAD

**Issue by demand2k** [braintree/braintree_android#156]
### General information

* SDK/Library version: 2.3.12
* Environment: Production
* Android Version and Device: I don't see any specific device. It happens on versions from 4x to 7x.

### Issue description
I don't know how to reproduce it, but It constantly happens to real users. I only see this log in our crash info collection system.

`android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:936)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:229)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at com.braintreepayments.api.internal.AnalyticsDatabase.addEvent(AnalyticsDatabase.java:61)
	at com.braintreepayments.api.BraintreeFragment$1.onConfigurationFetched(BraintreeFragment.java:475)
	at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:683)
	at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:617)
	at com.braintreepayments.api.BraintreeFragment$9.onConfigurationFetched(BraintreeFragment.java:643)
	at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:68)
	at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:286)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by lkorth** [comment]
Have you tried/encountered this same crash with the latest release (2.5.4)?

Is this in a regular app, or an Android Instant app?

**Comment by lkorth** [comment]
Closing due to lack of a response. Please comment if you are able to provide more information and we'll reopen it.
