### ISSUE TITLE
com.braintreepayments.api.exceptions.ConfigurationException: Request for configuration has failed: java.security.cert.CertPathValidatorException

### ISSUE THREAD

**Issue by francoisza** [braintree/braintree_android#163]
### General information

* SDK/Library version: 2.6.2 ( I specified 'com.braintreepayments.api:braintree:2+' in gradle)
* Android Version and Device: Android 4.4.4 Kitkat on a Sony D5103 (Sony Xperia T3)

### Issue description

Attempting to use paypal. 

I've tested this on a Samsung running Jellybean as well as another Samsung device running Kitkat 4.4.2. Also tested on Android 5 and above. All works fine.

I get the token. Create the braintree fragment. Then call the Paypal.authoriseAccount()

I get navigated to the paypal sandbox on a browser which is correct behaviour

As soon I as use the Sony Xperia T3 the following happens. I don't get navigated to the sandbox and the following exception is thrown from the braintreefragment. Any guidance would be appreciated.

```
Request for configuration has failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.. Future requests will retry up to 3 times
                                                                   com.braintreepayments.api.exceptions.ConfigurationException: Request for configuration has failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.. Future requests will retry up to 3 times
                                                                       at com.braintreepayments.api.BraintreeFragment$10.onResponse(BraintreeFragment.java:647)
                                                                       at com.braintreepayments.api.BraintreeFragment$10.onResponse(BraintreeFragment.java:643)
                                                                       at com.braintreepayments.api.ConfigurationManager$1.failure(ConfigurationManager.java:78)
                                                                       at com.braintreepayments.api.internal.HttpClient$4.run(HttpClient.java:299)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5124)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
                                                                       at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
                                                                       at com.android.okhttp.Connection.connect(Connection.java:107)
                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
                                                                       at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:254)
                                                                       at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:138)
                                                                       at com.braintreepayments.api.internal.HttpClient$1.run(HttpClient.java:155)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
                                                                    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:287)
                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:207)
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
                                                                       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
                                                                       at com.android.okhttp.Connection.upgradeToTls(Connection.java:146) 
                                                                       at com.android.okhttp.Connection.connect(Connection.java:107) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503) 
                                                                       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136) 
                                                                       at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:254) 
                                                                       at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:138) 
                                                                       at com.braintreepayments.api.internal.HttpClient$1.run(HttpClient.java:155) 
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:841) 
                                                                    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:287) 
                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:207) 
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612) 
                                                                       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406) 
                                                                       at com.android.okhttp.Connection.upgradeToTls(Connection.java:146) 
                                                                       at com.android.okhttp.Connection.connect(Connection.java:107) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296) 
                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503) 
                                                                       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136) 
                                                                       at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:254) 
                                                                       at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:138) 
                                                                       at com.braintreepayments.api.internal.HttpClient$1.run(HttpClient.java:155) 
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:841)

```

**Comment by sdcoffey** [comment]
Hey @francoisza,

Thanks for opening this issue. I'm curious to know if you've had this issue on any other devices besides the Sony Xperia T3. This sounds to me either like an issue with the bundled certificates on the device, or that the bundled version of OpenSSL on the device doesn't support TLS 1.2, which [is now enforced in Sandbox, and will be in Production soon.](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/)

To confirm which of the issues is more likely, you can try to reproduce this issue in production. If it doesn't surface in the same way, we can be reasonably sure that it is an compatibility mismatch between the version of OpenSSL bundled on the device and the version of TLS required in sandbox. Please let us know if there's any other relevant info here or if you're able to resolve this issue on that device.

**Comment by crookedneighbor** [comment]
Since we haven't gotten a response, I'm going to close this issue. Feel free to comment here if you need further assistance and I can re-open it.

**Comment by tony-o** [comment]
We're seeing this issue also, will provide more info once we investigate the SSL path -

**Comment by tony-o** [comment]
This can be closed, we tracked it down to a permissions issue elsewhere -
