### ISSUE TITLE
AriesCheckoutParams Class not found exception at runtime add payment hand-shake

### ISSUE THREAD

**Issue by cookseym** [braintree/braintree_android#168]
### General information

* SDK/Library version: 2.5.2
* Environment: Production
* Android Version and Device: Samsung S8 running 7.0
* Paypal App Version 6.17.1

### Issue description
Adding Paypal as a payment method in production kicks open the native paypal app.  
When using `PIN` as a verification method, I am able to get the nonce and add Paypal as a payment method to my application. 

The issue occurs when I use my fingerprint as a verification method within the paypal native app.
The progress bar spins after a successful fingerprint read, then the following screen and stacktrace occur.

![screenshot_20171023-084457](https://user-images.githubusercontent.com/5341500/31902785-b301d2b4-b7eb-11e7-9ec6-a57f75e140d5.png)

```
Class not found when unmarshalling: com.paypal.android.foundation.presentation.model.AriesCheckoutParams
   java.lang.ClassNotFoundException: com.paypal.android.foundation.presentation.model.AriesCheckoutParams
       at java.lang.Class.classForName(Native Method)
       at java.lang.Class.forName(Class.java:400)
       at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2374)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.BaseBundle.getString(BaseBundle.java:992)
       at android.content.Intent.getStringExtra(Intent.java:6733)
       at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:340)
       at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
       at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5898)
       at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5687)
       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3640)
       at android.os.Binder.execTransact(Binder.java:573)
    Caused by: java.lang.ClassNotFoundException: com.paypal.android.foundation.presentation.model.AriesCheckoutParams
       at java.lang.Class.classForName(Native Method)
       at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
       at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at java.lang.Class.classForName(Native Method) 
       at java.lang.Class.forName(Class.java:400) 
       at android.os.Parcel.readParcelableCreator(Parcel.java:2517) 
       at android.os.Parcel.readParcelable(Parcel.java:2471) 
       at android.os.Parcel.readValue(Parcel.java:2374) 
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2727) 
       at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
       at android.os.BaseBundle.getString(BaseBundle.java:992) 
       at android.content.Intent.getStringExtra(Intent.java:6733) 
       at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:340) 
       at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099) 
       at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5898) 
       at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5687) 
       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176) 
       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3640) 
       at android.os.Binder.execTransact(Binder.java:573) 
    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by bluk** [comment]
Thanks for the report. I have opened an internal issue for the app team.

**Comment by bluk** [comment]
@cookseym Does this error show up on other types of devices?

**Comment by cookseym** [comment]
@bluk , I have verified that the symptom exists for Samsung S6, and Google Pixel as well.  Same general stack trace, Class not found when unmarshalling: com.paypal.android.foundation.presentation.model.AriesCheckoutParams

**Comment by crookedneighbor** [comment]
Just a quick update, we've determined this is an issue on PayPal's end. We're working with them to get it resolved. When it is, it should just start working, no updates needed for the SDK.

**Comment by quinnjn** [comment]
This is an old issue and we haven't heard back from the PayPal's app team or the issue creator on whether is still active. 

I'm going to close this, if it is still an issue comment and we'll investigate.
