### ISSUE TITLE
com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity : java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by RohitE2logy** [braintree/braintree_android#171]
### General information

*  compile 'com.braintreepayments.api:braintree:2.+'
    compile 'com.braintreepayments.api:drop-in:2.+'

### Issue description

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.activpassholdings.activpass/com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity}: java.lang.IllegalArgumentException: A ThreeDSecureLookup must be specified with ThreeDSecureLookup.EXTRA_THREE_D_SECURE_LOOKUP extra
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.IllegalArgumentException: A ThreeDSecureLookup must be specified with ThreeDSecureLookup.EXTRA_THREE_D_SECURE_LOOKUP extra
       at com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity.onCreate(ThreeDSecureWebViewActivity.java:36)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by crookedneighbor** [comment]
@RohitE2logy Are you still having issues? Looks like some 3D Secure configuration is missing. Can you share your code?

**Comment by sdcoffey** [comment]
@RohitE2logy,

I'm closing this issue due to inactivity. Please file another issue if you're still being affected by this problem.
