### ISSUE TITLE
Crash from VisaCheckout Class

### ISSUE THREAD

**Issue by elainedizon** [braintree/braintree_android#175]
### General information

* SDK/Library version: 2.7.3
* Environment: Sandbox
* Android Version and Device: Oreo Pixel 2 Emulator

### Error/Crash from VisaCheckout Class

* Visa Checkout SDK Version: 5.5.2

Logs: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.braintreepayments.api.BraintreeFragment.waitForConfiguration(com.braintreepayments.api.interfaces.ConfigurationListener)' on a null object reference
       at com.braintreepayments.api.VisaCheckout.createProfileBuilder(VisaCheckout.java:60)
       at au.com.ozsale.login.LoginFragment$10$1.run(LoginFragment.java:259)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by quinnjn** [comment]
Braintree Android latest has only been tested with Visa Checkout 4.6. We mention this on our [Visa Checkout Client-Side Implementation](https://developers.braintreepayments.com/guides/visa-checkout/client-side/android/v2#visa-checkout) docs. It _may_ work with 5.5.2 but we haven't fully tested that.

It sounds like you're getting a `NullPointerException` where `mBraintreeFragment` is null and you're calling: `VisaCheckout.createProfileBuilder(mBraintreeFragment, this);`. The `BraintreeFragment` needs to be [initialized first](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#initialization).

If this does not solve your problem please post a code snippet of how you are creating a `BraintreeFragment` and feeding it into `VisaCheckout#createProfileBuilder`.

**Comment by crookedneighbor** [comment]
Going to close this since we haven't heard back. If you need further assistance, let us know and we can re-open it.
