### ISSUE TITLE
Do Not Read Disk on UI Thread.

### ISSUE THREAD

**Issue by sdoward** [braintree/braintree_android#179]
We use strict mode when developing so we get quick feedback on common mistakes. Our setup is like so...

```
StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
    .detectAll()
    .penaltyLog()
    .build())
```

We receive multiple stacktraces from Braintree

```
StrictMode policy violation; ~duration=11 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=1114143 violation=2
                                                                            at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
                                                                            at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1041)
                                                                            at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:595)
                                                                            at android.database.sqlite.SQLiteConnection.setAutoCheckpointInterval(SQLiteConnection.java:263)
                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:217)
                                                                            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
                                                                            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
                                                                            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                                            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
                                                                            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
                                                                            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                            at com.braintreepayments.api.internal.AnalyticsDatabase.addEvent(AnalyticsDatabase.java:61)
                                                                            at com.braintreepayments.api.BraintreeFragment$1.onConfigurationFetched(BraintreeFragment.java:467)
                                                                            at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:681)
                                                                            at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:615)
                                                                            at com.braintreepayments.api.BraintreeFragment$9.onConfigurationFetched(BraintreeFragment.java:641)
                                                                            at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:68)
                                                                            at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:286)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by bluk** [comment]
Which version of the SDK are you currently using? There was a fix applied to version [2.7.1](https://github.com/braintree/braintree_android/releases/tag/2.7.1) that should have resolved this issue. I recommend using the [latest SDK](https://github.com/braintree/braintree_android/releases), currently 2.8.1.

**Comment by sdoward** [comment]
Ah we are still using 2.6.2. Thanks for the quick response

**Comment by crookedneighbor** [comment]
Going to close this, since it looks like upgrading will fix the issue.
