### ISSUE TITLE
BrowserSwitchFragment ActivityNotFoundException

### ISSUE THREAD

**Issue by simonlinj** [braintree/braintree_android#195]
### General information

* SDK/Library version: only with 2.10.0
* Environment: Production
* Android Version and Device: 
    - Samsung Galaxy J1 - OS 5.1.1
    - LG M1 - OS 5.1.1
    - LG Phoenix 2 - OS 6.0
    - Alcatel 5085C - OS 7.0

### Issue description

Receiving a few crash reports after upgrading the SDK to 2.10.0. Had no issues on previews versions.

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://assets.braintreegateway.com/mobile/three-d-secure-redirect/0.1.4/index.html?AcsUrl=https://0eaf.cardinalcommerce.com/EAFService/jsp/v1/redirect&PaReq=P.8ccf9XXXXXXXXX&TermUrl=https://api.braintreegateway.com:443/merchants/XXXXXXXX/client_api/v1/payment_methods/XXXXXXXXX/three_d_secure/authenticate?authorization_fingerprint=XXXXX&authorization_fingerprint_64=XXXXXXXXX&ReturnUrl=https://assets.braintreegateway.com/mobile/three-d-secure-redirect/0.1.4/redirect.html?redirect_url=XXX.XXXXX.XXXXXX.braintree://x-callback-url/braintree/threedsecure? flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1404)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1386)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
       at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:137)
       at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:107)
       at com.braintreepayments.api.ThreeDSecure.launchBrowserSwitch(ThreeDSecure.java:218)
       at com.braintreepayments.api.ThreeDSecure.access$000(ThreeDSecure.java:35)
       at com.braintreepayments.api.ThreeDSecure$2$1.success(ThreeDSecure.java:153)
       at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by quinnjn** [comment]
This stack trace is telling us the devices doesn't have an activity that can handle opening a URL.

If you run the [Browser Switch Demo](https://github.com/braintree/browser-switch-android) on a device without any browsers installed you should see the same issue.

The action item I see here is we should add a check in [braintree/browser-switch-android](https://github.com/braintree/browser-switch-android) to verify an activity exists that can open a URL.

I don't think this issue is related to braintree_android so I'm going to close this issue and open one on [braintree/browser-switch-android](https://github.com/braintree/browser-switch-android/issues/4). Feel free to continue to comment there!

**Comment by simonlinj** [comment]
@quinnjn  thanks for the prompt reply.  

Will the 3D Secure work if I downgrade to 2.9.0?

**Comment by quinnjn** [comment]
Are these crashes coming from customers, or your tests?

I would imagine that most customers with an Android device would have a browser installed on their device.

**Comment by simonlinj** [comment]
crashes are coming from customers.  hard to imagine a smart phone without a browser, but there is quite a few.

my current workaround is to extend `ThreeDSecure` and enable webview override. 

```java
public class MyThreeDSecure  extends ThreeDSecure {

    static public void webViewOverride(boolean enable) {
        sWebViewOverride = enable;
    }
}
```

**Comment by quinnjn** [comment]
Very handy work around! 

I've reopened the issue and we'll explore this problem more. At the very least we'll make that override easier to access.

**Comment by quinnjn** [comment]
@simonlinj are you seeing the same exception for your customers using PayPal? PayPal would also use the browser switch library and have the same problem for customers without browsers.

**Comment by simonlinj** [comment]
didn't receive any crash report yet, because we are not activating Paypal as a payment method for all users.

**Comment by simonlinj** [comment]
but you are right, users without a browser installed will have the same exception with Paypal. unfortunally there is no webviewOverride option for Paypal.

**Comment by quinnjn** [comment]
We wouldn't be able to add a WebView for PayPal since [PayPal does not accept WebViews](https://developer.paypal.com/docs/classic/lifecycle/info-security-guidelines/#do-not-use-a-webview-to-display-paypal-web-pages-within-your-application).

I'm not up to date on the Cardinal Commerce (3DS) stance on WebViews, but I do know they are pushing for a 2.0 of the 3-D Secure service which may or may not have changed support for WebViews.

We're going to add the [proper error handling for this in browser-switch](https://github.com/braintree/browser-switch-android/issues/4), but if a customer is unable to open a browser and continue the browser-switch we would error back to the merchant and from there advise the customer to use a different payment method.
