### ISSUE TITLE
Crash on SDK 10 in FloatingLabelEditText when trying to focus next field.

### ISSUE THREAD

**Issue by darronschall** [braintree/braintree_android#20]
When the CardEditText tries to move the focus to the next field on an Android 2.3 device (SDK 10), a crash is experienced:

    FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: direction must be one of {FOCUS_UP, FOCUS_DOWN, FOCUS_LEFT, FOCUS_RIGHT}.
            at android.view.FocusFinder.isCandidate(FocusFinder.java:263)
            at android.view.FocusFinder.isBetterCandidate(FocusFinder.java:163)
            at android.view.FocusFinder.findNextFocus(FocusFinder.java:141)
            at android.view.FocusFinder.findNextFocus(FocusFinder.java:93)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:476)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.ViewGroup.focusSearch(ViewGroup.java:478)
            at android.view.View.focusSearch(View.java:3494)
            at com.braintreepayments.cardform.view.FloatingLabelEditText.focusNext(FloatingLabelEditText.java:168)
            at com.braintreepayments.cardform.view.CardEditText.afterTextChanged(CardEditText.java:83)
            at android.widget.TextView.sendAfterTextChanged(TextView.java:6330)

This happens on an HTX Nexus One running Android 2.3.6. I am using version 1.3.0 of the Braintree SDK.

**Comment by lkorth** [comment]
`View.FOCUS_FORWARD` is causing the crash [here](https://github.com/braintree/braintree_android/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/view/FloatingLabelEditText.java#L168). Odd since [FOCUS_FORWARD](http://developer.android.com/reference/android/view/View.html#FOCUS_FORWARD) is API level 1, although it does cause a lint error, but still works on newer devices.

We'll look into this and create a fix.

**Comment by lkorth** [comment]
Due to the very small usage of API levels < 15 that we've seen with the SDK, we will be changing the `minSdkVersion` and not fixing this bug.

**Comment by k-nar** [comment]
unlike ios there's still 20% of people who use old sdk : http://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/

wouldn't FOCUS_DOWN be just as good and fix this bug ?
or just wrap this code in a try catch and let people on older sdk select the next field themselves

this crash on isBetterCandidate
https://chromium.googlesource.com/android_tools/+/2dfa615c860119957bfd2a4711208087575cf92e/sdk/sources/android-21/android/view/FocusFinder.java#366

**Comment by lkorth** [comment]
According to that link, there are 7.4% of devices still on API 10, not 20% and [Google's official numbers](https://developer.android.com/about/dashboards/index.html) have it 5.6%.

`FOCUS_DOWN` does work on phones in portrait, but in landscape or on a tablet when the fields are next to each other instead below, `FOCUS_DOWN` does not work.

We'll look at adding exception handling to this functionality.

**Comment by k-nar** [comment]
thanks 
something I don't quite understand from the new separate repo the usage is  
cardForm.setRequiredFields(Activity.this, true, true, false, false, "Purchase");
but from the braintreeApi DropiIn repo 
https://github.com/braintree/braintree_android/blob/master/Drop-In/src/main/java/com/braintreepayments/api/dropin/AddPaymentMethodViewController.java#L76-77

mCardForm.setRequiredFields(true, true, mBraintree.isCvvChallenegePresent(),
                mBraintree.isPostalCodeChallengePresent(), getCustomizedCallToAction());

so the signature is different 

indeed I've done 
compile('com.braintreepayments:card-form:2.0.0')
    compile ('com.braintreepayments.api:braintree:1.+'){
        exclude group: 'com.braintreepayments', module: 'card-form'
    }
and  get java.lang.NoSuchMethodError: com.braintreepayments.cardform.view.CardForm.setRequiredFields

does this mean If I want to use card-form 2.0.0 I have to make my own DropIn Activity ?

**Comment by lkorth** [comment]
[Drop-in uses `card-form` 1.4.0](https://github.com/braintree/braintree_android/blob/master/Drop-In/build.gradle#L23), you're trying to use 2.0.0 which is a new major version with breaking changes. Drop-in has been updated to use 2.0.0 and will be available after the next release.
