### ISSUE TITLE
Illegal char <:> at index 1: \:PayPalDataCollector\build\libs\META-INF\MANIFEST.MF

### ISSUE THREAD

**Issue by Harvinkour** [braintree/braintree_android#228]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies:

**Comment by Harvinkour** [comment]
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 1: \:PayPalDataCollector\build\libs\META-INF\MANIFEST.MF
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.android.build.gradle.internal.packaging.ParsedPackagingOptions.getAction(ParsedPackagingOptions.java:135)
	at com.android.build.gradle.internal.transforms.MergeJavaResourcesTransform.lambda$transform$6(MergeJavaResourcesTransform.java:303)

**Comment by hibob224** [comment]
This issue begun for us with version 2.15.0, downgrading back to 2.14.2 has fixed it for now

**Comment by Epreuve** [comment]
@Harvinkour Thanks for the report.  We're looking into this now and will update when we push a fix.

**Comment by jcnotfound** [comment]
The message has changed, now it is "Illegal char <:> at index 0: :PayPalDataCollector/".

**Comment by Epreuve** [comment]
Thanks for the feedback everyone.  We're having some trouble replicating the specific issue and was wondering if anyone could confirm their OS, and provide a quick run down of the steps we can use to see the issue ourselves.  

We have a speculation as to the change causing it, but without steps to replicate we'd be guessing on the absolute fix.

**Comment by poojanOTR** [comment]
windows 10 for myself

**Comment by demerino** [comment]
@Harvinkour Release 2.15.1 which should fix the issue. Can you verify?

**Comment by Harvinkour** [comment]
yes, its working fine now.

Thanks, for resolving the issue.

Regards,
Harvin Dutta.

7827079311.

**Comment by poojanOTR** [comment]
Thanks, looks like its fix 👍

**Comment by quinnjn** [comment]
We released 2.15.2 which should have solved the NoClassDefFoundError for PayPalDataCollector. Let us know if there are still issues compiling this version!

**Comment by quinnjn** [comment]
Closing this issue, please comment if the issue still exists in 2.15.2
