### ISSUE TITLE
SDK v2.15.0 and 2.15.1 triggers DexFile error and java.lang.NoClassDefFoundError for PayPalDataCollector

### ISSUE THREAD

**Issue by williamli** [braintree/braintree_android#229]
### General information

* SDK/Library version: 2.15.*
* Environment: Sandbox
* Android Version and Device: Pixel 2 XL API 26
* Braintree dependencies: 
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation files('libs/android-smart-image-view-1.0.0.jar')
    implementation files('libs/httpmime-4.2.2.jar')
    implementation 'com.google.code.gson:gson:2.8.0'
    implementation 'com.braintreepayments.api:braintree:2.15.0'
    implementation 'com.loopj.android:android-async-http:1.4.9'
    implementation 'com.google.android.gms:play-services-wallet:+'

### Issue description
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.scstorage, PID: 6507
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/paypal/android/sdk/data/collector/PayPalDataCollector;
                      at com.paypal.android.sdk.onetouch.core.PayPalOneTouchCore.getClientMetadataId(PayPalOneTouchCore.java:139)
                      at com.paypal.android.sdk.onetouch.core.CheckoutRequest.pairingId(CheckoutRequest.java:54)
                      at com.braintreepayments.api.PayPal.getCheckoutRequest(PayPal.java:558)
                      at com.braintreepayments.api.PayPal$2.success(PayPal.java:246)
                      at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.paypal.android.sdk.data.collector.PayPalDataCollector" on path: DexPathList[[zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/base.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_resources_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.paypal.android.sdk.onetouch.core.PayPalOneTouchCore.getClientMetadataId(PayPalOneTouchCore.java:139) 
                      at com.paypal.android.sdk.onetouch.core.CheckoutRequest.pairingId(CheckoutRequest.java:54) 
                      at com.braintreepayments.api.PayPal.getCheckoutRequest(PayPal.java:558) 
                      at com.braintreepayments.api.PayPal$2.success(PayPal.java:246) 
                      at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288) 
                      at android.os.Handler.handleCallback(Handler.java:789) 
                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.scstorage-Q-ok2s1_uaClWYciJPZNjw==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
                      at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
                      at android.app.LoadedApk.getResources(LoadedApk.java:936)
                      at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      		... 5 more
Application terminated.
```

Works perfectly in 2.14.*.

**Comment by poojanOTR** [comment]
@williamli I've now changed my dependency to use 2.14.2 instead of using the latest version

**Comment by williamli** [comment]
@poojanOTR  me too

**Comment by poojanOTR** [comment]
Probably will change I use Braintree moving forward, in terms of using the latest version

**Comment by demerino** [comment]
We're working on a fix for this issue.

**Comment by breakline87** [comment]
I had the same problem, works with Braintree 2.14.2

**Comment by Logicoeur** [comment]
I was able to solve this by including 'com.google.android.instantapps:instantapps:1.1.0' as a dependency in Gradle

**Comment by quinnjn** [comment]
@robertoestivill we upload our artifacts to Maven Central. I believe JCenter pulls in Maven Central artifacts to host as a mirror. I'm not to sure why there is a delay for JCenter to grab a copy of 2.15.2 though.

In the meantime you could add `mavenCentral()` to your repository source list until JCenter updates this version.
