### ISSUE TITLE
SocketTimeout exceptions on certain Samsung Android Phones on mobile data network especially 4G networks

### ISSUE THREAD

**Issue by mathewbijo** [braintree/braintree_android#257]
### General information

* SDK/Library version: 3.1.0
* Environment:  Sandbox AND Production
* Android Version and Device: Samsung S8 with Android 8.0
* Braintree dependencies: 
implementation "com.braintreepayments.api:braintree:3.1.0"
implementation "com.braintreepayments.api:data-collector:2.0.0"

### Getting SocketTimeout exceptions on certain Samsung Android Phones on mobile data network especially 4G networks (works if switched to 3G or wifi) 

**This only happens in on Samsung S8 and S8+ as far as we know. 
Only happens in mobile data networks and not in wifi connections**

Steps to reproduce
Using PayPal Custom UI, redirect user to PayPal website in custom chrome tab.
User logs in and selects an account to link & Agrees to Billing Agreement.
On returning back to the Android App, PayPal SDK's `onError()` function is called with the Stacktrace below:
```
2019-06-21 09:59:16.556 20678-20678/au.com.bws.debug W/System.err: java.net.SocketTimeoutException: timeout
2019-06-21 09:59:16.562 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
2019-06-21 09:59:16.562 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
2019-06-21 09:59:16.562 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
2019-06-21 09:59:16.562 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
2019-06-21 09:59:16.562 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:385)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
2019-06-21 09:59:16.563 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:499)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:435)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:566)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:255)
2019-06-21 09:59:16.564 20678-20678/au.com.bws.debug W/System.err:     at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:137)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at com.braintreepayments.api.internal.HttpClient.post(HttpClient.java:219)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at com.braintreepayments.api.internal.BraintreeHttpClient.post(BraintreeHttpClient.java:120)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at com.braintreepayments.api.internal.HttpClient$2.run(HttpClient.java:186)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-06-21 09:59:16.565 20678-20678/au.com.bws.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-06-21 09:59:16.566 20678-20678/au.com.bws.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)

```

**Comment by quinnjn** [comment]
Keeping an eye on square/okhttp#3974 for this issue.

I don't think this is related but your Braintree dependencies should be the same version. Please upgrade data-collector to 3.1.0.

**Comment by sshropshire** [comment]
Hi @mathewbijo thanks for using the Braintree SDK for Android. Did upgrading to the latest version resolve your issue?

**Comment by sarahkoop** [comment]
Hi @mathewbijo following up on this - are you still experiencing this issue or did upgrading resolve?
