### ISSUE TITLE
Exception during AuthenticationManager construction during creating ArCore Session object

### ISSUE THREAD

**Issue by suraj-0387** [braintree/braintree_android#284]
Getting following issue when try to create Session Object of ARCore

E/ARCore-AuthenticationManager: Exception during AuthenticationManager construction: com.google.android.gms.common.GoogleApiAvailability
    java.lang.ClassNotFoundException: com.google.android.gms.common.GoogleApiAvailability
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.google.ar.persistence.AuthenticationManager.a(PG:72)
        at com.google.ar.persistence.AuthenticationManager.<init>(PG:4)
        at com.google.ar.persistence.AuthenticationManagerFactory.create(PG:3)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapper(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:5)
        at com.example.handtrackinggradle.MainActivity.startCamera(MainActivity.java:324)
        at com.example.handtrackinggradle.MainActivity.onResume(MainActivity.java:171)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
        at android.app.Activity.performResume(Activity.java:7609)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4013)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4053)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7076)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/com.example.handtrackinggradle-p0OQ0rOqD7I0DpvWKOl4_A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.handtrackinggradle-p0OQ0rOqD7I0DpvWKOl4_A==/lib/arm64, /data/app/com.example.handtrackinggradle-p0OQ0rOqD7I0DpvWKOl4_A==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:1

**Comment by scannillo** [comment]
Hi @suraj-0387. This looks to be an issue with [Google's Augmented Reality Framework ](https://arvr.google.com/arcore/?gclid=EAIaIQobChMIp8edy7zE5gIVD8ZkCh3BqgEIEAAYASAAEgJFTPD_BwE). 

I don't see how your issue pertains to Braintree. If there is an issue with the `Braintree Android SDK`, please open a new issue following the issue template provided.
