### ISSUE TITLE
Crash in `BraintreeFragment` after updating version from 3.12.0 to 3.13.0

### ISSUE THREAD

**Issue by hakanbagci** [braintree/braintree_android#308]
Hi,

### General Information
 
* SDK/Library version: Android SDK 3.13.0
* Environment: Production
* Android Version and Device: All Android versions with various devices
* Braintree dependencies: com.braintreepayments.api:braintree:3.13.0

### Issue description

After updating braintree Android SDK version from 3.12.0 to 3.13.0 we have started observing following exception in our crash logs which are related to `BraintreeFragment`. I think it is happening because activity is becoming `null` in some certain cases. 

This crash is infrequent but we are observing it with significant numbers. BTW, it started immediately after updating version from `3.12.0` to `3.13.0`. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
       at com.braintreepayments.api.BraintreeFragment.getReturnUrlScheme(BraintreeFragment.java:390)
       at com.braintreepayments.api.PayPal.populateRequestData(PayPal.java:513)
       at com.braintreepayments.api.PayPal.getCheckoutRequest(PayPal.java:459)
       at com.braintreepayments.api.PayPal$1.success(PayPal.java:171)
       at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

It seems that it is caused by the change done in new version (3.13.0). Here is the link to the change that causes the issue. 
https://github.com/braintree/braintree_android/compare/3.12.0...3.13.0#diff-1bdbc7e2b2f2abde9880e0096f30c698L387

**Comment by hakanbagci** [comment]
Hi @sshropshire, thanks for the quick response. This crash is happening rarely and unfortunately, we were not able to reproduce it. One more insight about the crash is that devices are always in the foreground.

**Comment by darkmode-cyber** [comment]
My apologies, I didn’t understand what I was doing

**Comment by sshropshire** [comment]
Hi @hakanbagci we provided a fix for this issue in or latest [v3.14.0](https://github.com/braintree/braintree_android/releases/tag/3.14.0) release.
