### ISSUE TITLE
BraintreeFragment NullPointerException

### ISSUE THREAD

**Issue by edwardharks** [braintree/braintree_android#309]
### General information

* SDK/Library version: 3.13.0
* Environment: production
* Android Version and Device: Android 9 & 10. Samsungs, Ziaomi, Huawei
* Braintree dependencies:
com.braintreepayments.api:braintree:3.13.0

### Issue description

After updating to 3.13.0 we are seeing the following crash in production. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
       at com.braintreepayments.api.BraintreeFragment.getReturnUrlScheme(BraintreeFragment.java:390)
       at com.braintreepayments.api.PayPal.populateRequestData(PayPal.java:513)
       at com.braintreepayments.api.PayPal.getBillingAgreementRequest(PayPal.java:476)
       at com.braintreepayments.api.PayPal$1.success(PayPal.java:169)
       at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by edwardharks** [comment]
Just noticed this https://github.com/braintree/braintree_android/issues/308
