### ISSUE TITLE
Upgrade cardinal commerce to androidx

### ISSUE THREAD

**Issue by calvarez-ov** [braintree/braintree_android#315]
### General information

* SDK/Library version: cardinal commerce 2.2.3-2
* Environment: Sandbox
* Android Version and Device: Android Emulator, API 30
* Braintree dependencies:
    ```
    com.braintreepayments.api:drop-in:5.0.0
    +--- com.braintreepayments.api:braintree:3.14.1
    |    +--- com.braintreepayments.api:google-payment:3.3.1
    |    +--- com.braintreepayments.api:core:3.14.1
    |    |    \--- com.braintreepayments:browser-switch:1.1.2 -> com.libon.android.braintreepayments:browser-switch:1.1.0-1+a8f62b9
    |    \--- com.paypal.android.sdk:paypal-one-touch:3.14.1
    |         +--- com.braintreepayments.api:core:3.14.1 (*)
    |         \--- com.paypal.android.sdk:data-collector:3.14.1
    +--- com.braintreepayments:card-form:5.0.0
    \--- com.braintreepayments.api:three-d-secure:3.14.1
         \--- org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.3-2
    ```

### Issue description

I finally removed (what I thought was) the last library in my project which still used the deprecated support library. So, I disabled jetifier by making this change to my `gradle.properties` file:
```patch
-android.enableJetifier=true
+android.enableJetifier=false
```
My app compiled and installed fine, but when calling `ThreeDSecure.performVerification()`, the app crashed:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.cardinalcommerce.shared.cs.f.h.<init>(Unknown Source:27)
        at com.cardinalcommerce.shared.cs.f.c.a(Unknown Source:2)
        at com.cardinalcommerce.shared.cs.f.c.<init>(Unknown Source:17)
        at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:2)
        at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:11)
        at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:124)
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24)
        at com.braintreepayments.api.ThreeDSecure.configureCardinal(ThreeDSecure.java:391)
        at com.braintreepayments.api.ThreeDSecure.access$100(ThreeDSecure.java:47)
        at com.braintreepayments.api.ThreeDSecure$4.onConfigurationFetched(ThreeDSecure.java:220)
        at com.braintreepayments.api.BraintreeFragment$14.run(BraintreeFragment.java:886)
        at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:809)
        at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:878)
        at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:185)
```

This indicates that the cardinal commerce library still hasn't migrated to androidx. It would be great if they could, so we could disable jetifier (one less build phase is always welcome).

Thanks!

**Comment by sshropshire** [comment]
Hi @calvarez-ov thanks for filing this issue. We've notified our MPI provider and will post information here when once we get more information.

**Comment by calvarez-ov** [comment]
Just for info, this is still a problem with version 2.2.4-1 of the library.

**Comment by sshropshire** [comment]
@calvarez-ov correct. We were notified that Cardinal's `androidx` migration will be completed in a future release.

**Comment by krunk4ever** [comment]
Awesome, can you update this thread or include it in the release notes when it happens? We just got bit by this too because we removed jetifier from our app and didn't realize Cardinal depended on it.

**Comment by calvarez-ov** [comment]
Just for info, this is still a problem with version 2.2.5-1 of the library.

**Comment by sshropshire** [comment]
Hi @calvarez-ov correct, yes. We're still coordinating efforts with our MPI to migrate over to androidx. We don't have an exact timeline, but it is on their radar.

**Comment by calvarez-ov** [comment]
Just for info, this is still a problem with version 2.2.5-2 of the library.

**Comment by sshropshire** [comment]
@calvarez-ov we're still waiting for `androidx` support from our MPI. It is still on the roadmap.

**Comment by Abdelsattar** [comment]
Is there exist any workaround to make ThreeDSecure with an android-x project as I have the same problem in v3?

**Comment by sarahkoop** [comment]
@Abdelsattar You can set `android.enableJetifier=true` in your `gradle.properties` to use ThreeDSecure in an androidx project.
