### ISSUE TITLE
3ds screen crash when click on edittext field

### ISSUE THREAD

**Issue by haibui-parkman** [braintree/braintree_android#327]
### General information

* SDK/Library version: braintreeVersion : 3.15.0, braintree-drop-in: 5.0.2
* Environment: Production
* Android Version and Device: Samsung J3, Samsung A6
* Braintree dependencies:
 "com.braintreepayments.api:braintree:3.15.0"
 "com.braintreepayments.api:drop-in:5.0.2"

### Issue description

On some devices, for example in this case we were able to reproduce using Samsung J3 and A6, after enter payment card and paymentnoncecreated, user was taken to braintree 3ds version 2, when user clicked on the edittext field to enter bank id (This case was Nordea bank), the 3ds view crashed. Here is the crash log: 

`
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
         at android.text.BoringLayout.isBoring(BoringLayout.java:329)
         at android.widget.TextView.makeSingleLayout(TextView.java:9454)
         at android.widget.TextView.makeNewLayout(TextView.java:9308)
         at android.widget.TextView.assumeLayout(TextView.java:9203)
         at android.widget.TextView.onProvideAutoStructureForAssistOrAutofill(TextView.java:11892)
         at android.widget.TextView.onProvideAutofillStructure(TextView.java:11869)
         at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:9437)
         at android.view.View.dispatchProvideAutofillStructure(View.java:9430)
         at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:4362)
         at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:4362)
         at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:517)
         at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
         at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3425)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
         at android.os.Handler.dispatchMessage(Handler.java:106)
         at android.os.Looper.loop(Looper.java:216)
         at android.app.ActivityThread.main(ActivityThread.java:7211)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
`
![ezgif-2-5be8159ed7a5](https://user-images.githubusercontent.com/23192294/104950949-4755c000-59ca-11eb-8270-a31cb5ae8368.gif)

**Comment by hollabaq86** [comment]
👋 @haibui-parkman please [contact Support](https://help.braintreepayments.com/) referencing this issue. They will partner with our 3DS MPI provider CardinalCommerce to escalate this issue to the card networks and ultimately Nordea.

**Comment by akitep** [comment]
Sorry for commenting closed issue, but @haibui-parkman I would be interested to hear if you were able to resolve this issue? We're having the same problem, not using Braintree, but CardinalCommerce is our provider also.

**Comment by akitep** [comment]
This problem has been fixed in the CardinalCommerce Android SDK version 2.2.5-2 (released 23 March 2021) https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/11862033/Cardinal+Mobile+SDK+-+Android. At least we haven't been able to reproduce the problem anymore with this update. (still we're not using Braintree, but just to let you know that most probably you'll need a new Braintree version with this CardinalCommerce SDK update)

**Comment by sarahkoop** [comment]
Version [`3.17.2`](https://github.com/braintree/braintree_android/releases) of the Braintree Android SDK has been released with Cardinal version `2.2.5-2`
