### ISSUE TITLE
GoogleApiAvailabliity class not found

### ISSUE THREAD

**Issue by norman-kapschefsky** [braintree/braintree_android#34]
Hi,
since your last update 2 days ago (1.6) I get a NoClassDefFoundErrorexception on a google service.

With version 1.5.1 everything is fine.

Thanks in advance for investigating ...

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
            at com.braintreepayments.api.BraintreeApi.isAndroidPayEnabled(BraintreeApi.java:164)
            at com.braintreepayments.api.Braintree.isAndroidPayEnabled(Braintree.java:333)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:95)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:75)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.initViews(AddPaymentMethodViewController.java:69)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.<init>(AddPaymentMethodViewController.java:54)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.initAddPaymentMethodView(BraintreePaymentActivity.java:332)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:323)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.onPaymentMethodsUpdated(BraintreePaymentActivity.java:205)
            at com.braintreepayments.api.Braintree$12$1.run(Braintree.java:1119)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/net.fashionfreax-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.braintreepayments.api.BraintreeApi.isAndroidPayEnabled(BraintreeApi.java:164)
            at com.braintreepayments.api.Braintree.isAndroidPayEnabled(Braintree.java:333)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:95)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:75)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.initViews(AddPaymentMethodViewController.java:69)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.<init>(AddPaymentMethodViewController.java:54)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.initAddPaymentMethodView(BraintreePaymentActivity.java:332)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:323)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.onPaymentMethodsUpdated(BraintreePaymentActivity.java:205)
            at com.braintreepayments.api.Braintree$12$1.run(Braintree.java:1119)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.GoogleApiAvailability
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 19 more
```

**Comment by lkorth** [comment]
Thanks for the report @norman-kapschefsky. `1.6.1` was just released with a fix for this.

**Comment by rubinikuttyomkumar** [comment]
Hi, 
 It still happens with api build 1.6.4 . 
FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.google.android.gms.common.GoogleApiAvailability
            at com.braintreepayments.api.BraintreeApi.isAndroidPayEnabled(BraintreeApi.java:166)
            at com.braintreepayments.api.Braintree.isAndroidPayEnabled(Braintree.java:334)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:99)
            at com.braintreepayments.api.dropin.view.PaymentButton.initialize(PaymentButton.java:79)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.initViews(AddPaymentMethodViewController.java:74)
            at com.braintreepayments.api.dropin.AddPaymentMethodViewController.<init>(AddPaymentMethodViewController.java:54)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.initAddPaymentMethodView(BraintreePaymentActivity.java:332)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:323)
            at com.braintreepayments.api.dropin.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:300)
            at android.os.Handler.handleCallback(Handler.java:800)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by lkorth** [comment]
You're right, the error was not properly being caught, `1.6.5` was just released to [fix this](https://github.com/braintree/braintree_android/commit/b274f5cf369efc22ef01472cb3049b4429e73b92).

**Comment by IgorGanapolsky** [comment]
@lkorth I am curious - what was the solution?  I am facing this error today.

**Comment by suraj-0387** [comment]
Add  implementation 'com.google.android.gms:play-services-auth:17.0.0'

**Comment by scannillo** [comment]
@suraj-0387 This issue is closed, and I don't see how your comment relates. If you believe there is an issue with our SDK, you can open a new issue and fill out our issue template. For help troubleshooting your integration, reach out to [Braintree Support](https://help.braintreepayments.com/). Thanks!
