### ISSUE TITLE
SecurityException when calling performVerification on a ThreeDSecureClient

### ISSUE THREAD

**Issue by matejhacin** [braintree/braintree_android#474]
### General information

* SDK/Library version: 4.7.0
* Environment: Production and Sandbox
* Android Version and Device: Android 12, Pixel 5
* Braintree dependencies:
- com.braintreepayments.api:three-d-secure:4.7.0
- com.braintreepayments:card-form:4.3.0

### Issue description

There is a very weird crash happening in my app since upgrading to Android 12, and it seems to be crashing somewhere inside the Braintree SDK, every time I call `ThreeDSecureClient.performVerification(activity, request, callback)`

`java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@fed5b655: getAddress
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetoothManager$Stub$Proxy.getAddress(IBluetoothManager.java:773)
        at android.bluetooth.BluetoothAdapter.getAddress(BluetoothAdapter.java:1279)
        at com.cardinalcommerce.shared.cs.f.b.<init>(Unknown Source:23)
        at com.cardinalcommerce.shared.cs.f.g.b(Unknown Source:69)
        at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:7)
        at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:2)
        at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:132)
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24)
        at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:62)
        at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21)
        at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:104)
        at com.braintreepayments.api.ConfigurationLoader$1.onResult(ConfigurationLoader.java:52)
        at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:123)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:2918)
        at com.android.server.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:2936)
        at com.android.server.BluetoothManagerService.getAddress(BluetoothManagerService.java:1703)
        at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:365)
        at android.os.Binder.execTransactInternal(Binder.java:1179)`

I am very confused by this as I don't understand why this would have anything to do with Braintree SDK? Why would this library want to have a Bluetooth permission?

Other info that might help:
- This started happening on Android 12
- I did not yet confirm if it happens on all or only some Android 12 devices
- My app indeed does use Bluetooth and I do have all required Bluetooth permissions inside the manifest, including BLUETOOTH_CONNECT related to this crash
- There is no other Bluetooth related code being called at the time when this happens. 3DS performVerification is the only process really happening in the app
- If I wrap the `performVerification` block of code inside try catch, it still crashes and Exception is not caught

**Comment by sshropshire** [comment]
Hi @matejhacin thanks for using the Braintree SDK for Android. We've contacted Cardinal, our 3rd-party MPI. We'll provide updates here in the future.

**Comment by matejhacin** [comment]
Thank you @sshropshire. Do you maybe have any idea how to work around this while we wait for further solution? Our users on Android 12 have trouble paying for our services and it's causing a lot of issues.

**Comment by solrace** [comment]
Hello **Matej:** Would you be able to confirm the use of the "manifest" and entries?
Here is the "code snippet" that demonstrates how to declare Bluetooth related permissions you app to target Android 12 and higher.
![image](https://user-images.githubusercontent.com/94066219/141148026-74389bd2-1789-4949-a6e3-36ba3b985c2b.png)

**Comment by matejhacin** [comment]
Hi @solrace. Thanks for the reply, the documentation screenshot you shared actually helped me get to the solution!

These were my permissions before (crash):


    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

The crash disappears after changing it to:

    <uses-permission android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

So for anyone running into the same issue, the trick is to add the `maxSdkVersion ` where necessary. Adding `BLUETOOTH_CONNECT` only is not the solution.

**Comment by bm185178** [comment]
Why braintree is using bluetooth? Our app does not support bluetooth permission. We need better answer. 
![Screen Shot 2021-11-12 at 12 13 00 PM](https://user-images.githubusercontent.com/66744335/141507415-4aabc0fe-6d85-44de-a979-7563c47286ff.png)

**Comment by sshropshire** [comment]
@bm185178 it's actually an issue with a 3rd-party dependency we use for fraud detection. We've notified our MPI of the issue. We'll post here when we receive an update.

**Comment by bm185178** [comment]
Any progress?

**Comment by sarahkoop** [comment]
@bm185178 The Cardinal SDK team is still investigating this issue. We will post here when we have more information. We appreciate your patience.

**Comment by bm185178** [comment]
It has been two weeks. Any progress?

**Comment by sarahkoop** [comment]
We are continuing to follow up with our MPI provider. We don't have any update yet, but will post here when we have more information. Thank you for your continued patience.

**Comment by sarahkoop** [comment]
Hi everyone - We've received an update from Cardinal that they have a fix for this that is targeted to be included in their `2.2.6-2` release. We do not have an exact date for that release, but will post an update here when we have the fix!

**Comment by bm185178** [comment]
Any news or update?

**Comment by sarahkoop** [comment]
This fix is still targeted to be included in their `2.2.6-2` release which is tentatively scheduled for March 2022. We will post an update here when we have the fix. We appreciate your continued patience!

**Comment by sarahkoop** [comment]
Hi all - Cardinal has provided us with a release that includes a fix for this issue, and we have released a new version of the SDK including this upgrade. Please update to version `4.10.0`. Please re-open this ticket if you are still experiencing this issue after updating.

**Comment by bm185178** [comment]
When drop-in sdk version 6 will be updated to support 4.10.0? Right not it is crashing 
```
 java.lang.NoSuchMethodError: No virtual method getAuthorization()Lcom/braintreepayments/api/Authorization; in class Lcom/braintreepayments/api/BraintreeClient; or its super classes (declaration of 'com.braintreepayments.api.BraintreeClient' appears 
```

**Comment by josephyanks** [comment]
Hi @sarahkoop - We are still experiencing this issue after upgrading to `4.11.0`. I've also verified that it still occurs when we update our `AndroidManifest.xml` to:

```
<uses-permission android:name="android.permission.BLUETOOTH"
    android:maxSdkVersion="30"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
    android:maxSdkVersion="30"/>
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```

Repeated attempts to complete the transaction do sometimes succeed.

Please let me know what additional information you'd need to help troubleshoot.

**Comment by sviro** [comment]
Hi @sarahkoop, we also are still experiencing this issue with 4.11.0 (even with 4.10.1). Maybe the problem is that you mentioned earlier that the fix should be included in  2.2.6-2 version of cardinal lib, but when I looked into your build.gradle, you are referencing 2.2.6-1.

**Comment by sviro** [comment]
Hi @sarahkoop, I've just tried your latest version (4.12.0), which has included 2.2.6-2 of cardinal lib, but unfortunately this version is still crashing on "Need BLUETOOTH_CONNECT permission". What should be our next steps to resolve this issue?

**Comment by sshropshire** [comment]
Hi @sviro we'll have to forward this information to Cardinal. Can you provide an updated stack trace so we can pass it along?

**Comment by sviro** [comment]
Hi @sshropshire, here is the stack trace:

```
java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@8c67d26e: getAddress
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
        at android.os.Parcel.createException(Parcel.java:2410)
        at android.os.Parcel.readException(Parcel.java:2393)
        at android.os.Parcel.readException(Parcel.java:2335)
        at android.bluetooth.IBluetoothManager$Stub$Proxy.getAddress(IBluetoothManager.java:773)
        at android.bluetooth.BluetoothAdapter.getAddress(BluetoothAdapter.java:1279)
        at com.cardinalcommerce.a.setLines.<init>(:46)
        at com.cardinalcommerce.a.setLineHeight.Cardinal(:88)
        at com.cardinalcommerce.a.setLineHeight.cca_continue(:52)
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(:5039)
        at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:62)
        at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21)
        at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:171)
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
        at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:165)
        at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
        at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:174)
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:161)
        at com.braintreepayments.api.ThreeDSecureClient.performVerification(ThreeDSecureClient.java:133)
        at com.braintreepayments.api.DropInClient.performThreeDSecureVerification(DropInClient.java:208)
        at com.braintreepayments.api.DropInActivity.lambda$onVaultedPaymentMethodSelected$14$com-braintreepayments-api-DropInActivity(DropInActivity.java:462)
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda8.onResult(Unknown Source:4)
        at com.braintreepayments.api.DropInClient.lambda$shouldRequestThreeDSecureVerification$3$com-braintreepayments-api-DropInClient(DropInClient.java:242)
        at com.braintreepayments.api.DropInClient$$ExternalSyntheticLambda12.onResult(Unknown Source:4)
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
        at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:165)
        at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
        at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:174)
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:161)
        at com.braintreepayments.api.DropInClient.shouldRequestThreeDSecureVerification(DropInClient.java:234)
        at com.braintreepayments.api.DropInActivity.onVaultedPaymentMethodSelected(DropInActivity.java:460)
        at com.braintreepayments.api.DropInActivity.onDropInEvent(DropInActivity.java:152)
        at com.braintreepayments.api.DropInActivity.lambda$onCreate$0$com-braintreepayments-api-DropInActivity(DropInActivity.java:88)
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda0.onFragmentResult(Unknown Source:2)
```

**Comment by xiaxiayige** [comment]
+1

sdk verison : **4.12.0** 
android version : **12** 

Error Stack

`07-25 11:13:46.813 25796 25796 E AndroidRuntime: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10344, packageName =xxx, attributionTag = null, token = android.os.BinderProxy@733a793, next = null }: getAddress
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2404)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2346)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.bluetooth.IBluetoothManager$Stub$Proxy.getAddress(IBluetoothManager.java:1165)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at android.bluetooth.BluetoothAdapter.getAddress(BluetoothAdapter.java:2326)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.cardinalcommerce.a.setLines.<init>(:46)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.cardinalcommerce.a.setLineHeight.Cardinal(:88)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.cardinalcommerce.a.setLineHeight.cca_continue(:52)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(:5039)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:62)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:171)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:165)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:174)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:161)
07-25 11:13:46.813 25796 25796 E AndroidRuntime:        at com.braintreepayments.api.ThreeDSecureClient.performVerification(ThreeDSecureClient.java:133)`

add the following permissions, works fine

`<uses-permission  android:name="android.permission.BLUETOOTH"android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />`

**Comment by sviro** [comment]
Hi @sshropshire, it has been two and a half month since my last comment with the stack trace. Is there any progress? In the meantime, I've tried also the latest version (4.15.0), but still the same crash is occuring. For us, this "add Bluetooth permission" hack is not a valid solution, since we don't want to add bluetooth permission to our application.

**Comment by sshropshire** [comment]
Hi @sviro thanks for your patience. I've notified Cardinal again and made sure to point out the stack trace. They mentioned that `2.2.6-1` fixed the original issue, but my guess is they'll need to investigate further to make sure Bluetooth permissions are enabled before accessing those Android APIs.

**Comment by sviro** [comment]
Hi, just to clarify, the mentioned crash happens when we try to call DropInClient.launchDropInForResult(), where ThreeDSecureRequest is set to the DropInRequest
