### ISSUE TITLE
Google Pay crash when using 4.10.0 in some cases

### ISSUE THREAD

**Issue by Hector1990** [braintree/braintree_android#543]
### General information

* SDK/Library version: 4.10.0
* Environment: Production
* Android Version and Device: Many devices, such as Galaxy A12 with Android 11

### Issue description

When we are going to launch Google pay in version 4.10.0. It will crash sometimes.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
       at com.braintreepayments.api.GooglePayLifecycleObserver.launch(GooglePayLifecycleObserver.java:44)
       at com.braintreepayments.api.GooglePayClient$4$1.onResult(GooglePayClient.java:296)
       at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
       at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:161)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:170)
       at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:157)
       at com.braintreepayments.api.GooglePayClient$4.onAuthorizationResult(GooglePayClient.java:275)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:170)
       at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:271)
       at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:228)
      .....
```

**Comment by sarahkoop** [comment]
Hi @Hector1990 - Could you provide a code snippet of your Google Pay integration?

**Comment by Hector1990** [comment]
@sarahkoop Hi, I skip some business logic codes.

```
class GooglePayBraintreeHostActivity : BraintreeHostActivity(), GooglePayListener {
    
    @VisibleForTesting
    internal val googlePayClient: GooglePayClient by lazy {
        GooglePayClient(this, BraintreeClient(this, "authKey"))
            .apply {
                setListener(this@GooglePayBraintreeHostActivity)
            }
    }

    override fun startPaymentRequest() {
        val googlePayRequest = createGooglePayRequest(
            getBraintreeAttributeExtra() as GooglePayBraintreeAttribute
        )

        googlePayClient.requestPayment(this, googlePayRequest)
    }

    override fun onGooglePaySuccess(paymentMethodNonce: PaymentMethodNonce) {
        // Will handle the success nonce and finish
    }

    override fun onGooglePayFailure(error: Exception) {
        // Will handle the error and finish
    }

    private fun createGooglePayRequest(
        attribute: GooglePayBraintreeAttribute
    ): GooglePayRequest {
        return GooglePayRequest().apply {
            isEmailRequired = true
            isPayPalEnabled = false
            transactionInfo = buildTransactionInfo(getAmountToPayExtra())
            billingAddressFormat = getBillingAddressFormat(attribute.billingAddressFormat)
            isBillingAddressRequired = attribute.billingAddressRequired
        }
    }

    private fun buildTransactionInfo(amountToPay: Amount): TransactionInfo {
        return TransactionInfo.newBuilder()
            .setTotalPrice("${amountToPay.value}")
            .setCurrencyCode(amountToPay.currency)
            .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
            .build()
    }

    private fun getBillingAddressFormat(billingAddressFormat: String): Int {
        return if (billingAddressFormat == "FULL") {
            WalletConstants.BILLING_ADDRESS_FORMAT_FULL
        } else {
            WalletConstants.BILLING_ADDRESS_FORMAT_MIN
        }
    }

    private fun getAmountToPayExtra(): Amount =
        intent.getParcelableExtra(AMOUNT_TO_PAY_EXTRA)!!
}

```

**Comment by sshropshire** [comment]
Hi @Hector1990 does the `GooglePayClient` get instantiated in `onCreate`? I know it's marked `lazy` in the example but the new [Activity Result API](https://developer.android.com/training/basics/intents/result) requires registration by at least `onCreate`. We migrated to this method internally since `startActivityForResult` is now deprecated.

**Comment by sshropshire** [comment]
@Hector1990 got it. Is the best way to reproduce this to turn off Wifi? Or are you seeing configuration fetches fail often?

**Comment by Hector1990** [comment]
Maybe you can use a sandbox tokenization in product env. I can reproduce it in this way.

**Comment by sshropshire** [comment]
@Hector1990 Yeah I'm trying to think of how this is possible (should lead to a potential fix if we need it). But fundamentally it looks like the SDK is attempting to launch GooglePay before we're able to [register the activity launcher](https://github.com/braintree/braintree_android/blob/c4bf27878725edaff705617ac6a617f98530cf8a/GooglePay/src/main/java/com/braintreepayments/api/GooglePayLifecycleObserver.java#L34).

**Comment by Hector1990** [comment]
Hi @sshropshire , is there any update about this issue?

**Comment by sshropshire** [comment]
Hi @Hector1990 could you provide a small demo re-creating the issue?

**Comment by Hector1990** [comment]
Hi @sshropshire  You can use an activity (call it `MainActivity`) to launch the `GooglePayHostActivity` which is used to launch Braintree SDK. Then you set the launch mode of  `MainActivity` to `singleTop`. 
In this case, it will crash.

**Comment by Hector1990** [comment]
Hi @sshropshire, a new hint. Whenever I first launch Google Pay firstly, it works fine. But then I canceled the payment; then I wanted to relaunch it, and it crashed. I am not sure if it's related to the duration of the configuration time loading. Maybe the SDK gets the configuration from the cache the second time. At that time, the activity launcher had not been registered?

Just a guess.

**Comment by Hector1990** [comment]
Hi @sshropshire, is there any update about this issue? We got more crashes in the production.

<img width="599" alt="CleanShot 2022-05-22 at 09 32 50@2x" src="https://user-images.githubusercontent.com/14172847/169674513-92e94072-6109-456e-a0cf-1af35b9fe431.png">


```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
  at com.braintreepayments.api.GooglePayLifecycleObserver.launch(GooglePayLifecycleObserver.java:44)
  at com.braintreepayments.api.GooglePayClient$4$1.onResult(GooglePayClient.java:296)
  at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
  at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:161)
  at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
  at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:170)
  at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:157)
  at com.braintreepayments.api.GooglePayClient$4.onAuthorizationResult(GooglePayClient.java:275)
  at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
  at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:170)
  at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:271)
  at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:228)
  at com.booking.payment.component.core.directintegration.braintree.googlepay.GooglePayBraintreeHostActivity.startPaymentRequest(GooglePayBraintreeHostActivity.kt:68)
  at com.booking.payment.component.core.directintegration.braintree.BraintreeHostActivity.onCreate(BraintreeHostActivity.kt:81)
  at android.app.Activity.performCreate(Activity.java:8207)
  at android.app.Activity.performCreate(Activity.java:8191)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
```

**Comment by sshropshire** [comment]
@Hector1990 Still looking to reproduce and I'm unable to in the Demo app, but the root cause may be because request payment is being called in `onCreate` as well.

The lifecycle observer is notified immediately after `onCreate` that the lifecycleOwner is in a `CREATED` state, and it may not have the opportunity to register for an activity result in time.

**Comment by Hector1990** [comment]
@sshropshire Hi, is there any update for this issue? If not, I will revert our Google Pay implementation to the previous version.

**Comment by sshropshire** [comment]
@Hector1990 the culprit here seems to be lazy instantiation of the `GooglePayClient` outside of `onCreate`. Does it work when this portion of the code is moved to `onCreate`?

```kotlin
GooglePayClient(this, BraintreeClient(this, "authKey"))
  .apply {
    setListener(this@GooglePayBraintreeHostActivity)
  }
```

**Comment by Hector1990** [comment]
@sshropshire Hi, the lazy instantiation of the `GooglePayClient` is inside of `onCreate`. Now it's initialized in `startPaymentRequest `, and `startPaymentRequest ` is called in `onCreate`.

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.braintree_host_activity)

        if (!hasIntentExtras()) {
            finishWithoutAnimation()
            return
        }

        if (savedInstanceState == null) {
            startPaymentRequest()
        }
    }
```

**Comment by sshropshire** [comment]
As an experiment, can we try this in `onCreate`?

```kotlin
// late initialization
googlePayClient = GooglePayClient(this, BraintreeClient(this, "authKey"))
  .apply {
    setListener(this@GooglePayBraintreeHostActivity)
  }

// then
Handler(Looper.getMainLooper()).post { 
  googlePayClient.requestPayment(this, googlePayRequest)
}
```

I know this conflicts with your current style, but I'd like to verify something. I believe in your use case the launcher isn't available because the observer won't be notified `onCreate` is finished until immediately after the method itself is finished.

**Comment by contissi** [comment]
Any update? Having the same issue after upgrading to 4.14.0. Converted Venmo and PayPal as well without issue.

```
class GooglePayActivity: AppCompatActivity(), GooglePayListener {

    private lateinit var braintreeClient: BraintreeClient
    private lateinit var googlePayClient: GooglePayClient

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        braintreeClient = BraintreeClient(this, "token")
        googlePayClient = GooglePayClient(this, braintreeClient)
        googlePayClient.setListener(this)

        when (val requestCode = intent.getIntExtra("requestCode", 0)) {
            GOOGLE_PAY_TOKEN_CODE -> {
                tokenizeGooglePay()
            }
            else -> {
                val result = Intent()
                result.putExtra("error", "Invalid request type: $requestCode")
                setResult(2, result)
                finish()
            }
        }
    }

    private fun tokenizeGooglePay() {
        val total = intent.getDoubleExtra("total", 0.0)

        val paymentRequest = GooglePayRequest()
        paymentRequest.transactionInfo = TransactionInfo.newBuilder()
            .setTotalPrice(total.toString())
            .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
            .setCurrencyCode("USD")
            .build()

        paymentRequest.isBillingAddressRequired = true

        googlePayClient.requestPayment(this, paymentRequest)
    }

    override fun onGooglePaySuccess(paymentMethodNonce: PaymentMethodNonce) {
        val result = Intent()
        result.putExtra("nonce", paymentMethodNonce.string)
        setResult(Activity.RESULT_OK, result)
        finish()
    }

    override fun onGooglePayFailure(error: Exception) {
        if (error is UserCanceledException) {
            val result = Intent();
            result.putExtra("nonce", null as String?)
            setResult(Activity.RESULT_OK, result)
            finish()
        } else {
            val result = Intent()
            result.putExtra("error", error.message)
            setResult(2, result)
            finish()
        }
    }

    override fun onNewIntent(newIntent: Intent?) {
        super.onNewIntent(newIntent)
        intent = newIntent
    }
}
```

Error (does not occur every time like stated above):
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
    at com.braintreepayments.api.GooglePayLifecycleObserver.launch(GooglePayLifecycleObserver.java:44)
    at com.braintreepayments.api.GooglePayClient$4$1.onResult(GooglePayClient.java:296)
    at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
    at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:165)
    at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
    at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:174)
    at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:161)
    at com.braintreepayments.api.GooglePayClient$4.onAuthorizationResult(GooglePayClient.java:275)
    at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
    at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:174)
    at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:271)
    at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:228)
    ........
```

**Comment by contissi** [comment]
@sshropshire I just tried your suggestion of wrapping the requestPayment:
```kotlin
Handler(Looper.getMainLooper()).post { 
  googlePayClient.requestPayment(this, googlePayRequest)
}
```

This did seem to work. I have yet to see a crash. Is this the suggested solution then? Also, should this be applied to other requests like PayPal/Venmo even though they seemingly do not have the same issue?

**Comment by sshropshire** [comment]
@contissi it may be specific to Google Pay here. The workaround could be removed if `tokenize` were called in response to a user action e.g. a "Google Pay" button press, only because the host activity will presumably be in a `RESUMED` state.

We use [Jetpack Lifecycle](https://developer.android.com/topic/libraries/architecture/lifecycle) internally to register for an activity result in `onCreate`. The `Handler` workaround is a bit of a hack to get the code to execute on the next run loop, which will be executed after all of the pending lifecycle methods i.e. `onCreate`, `onResume` etc. have completed synchronously.

For now it is a good workaround. In the future, we should offer explicit support for `onCreate` tokenization by capturing a pending `GooglePayRequest` internally which will allow the SDK to defer launching the Google Pay flow until after Activity result registration is complete.

**Comment by Hector1990** [comment]
I resolved this by:

1. init google pay client in `onCreate`
2. request payment in 'onStart'
