### ISSUE TITLE
Crash when user verifies their 2FA method when verifying card with ThreeDSecure

### ISSUE THREAD

**Issue by Gimbergsson** [braintree/braintree_android#545]
* SDK/Library version: 4.10.1
* Environment: Sandbox
* Android Version and Device: Pixel 6 Pro with Android 12
* Braintree dependencies:
com.braintreepayments:popup-bridge:3.0.0
com.braintreepayments.api:three-d-secure:4.10.1

### Issue description

Hello, I've implemented ThreeDSecure and I've got it to work on cards that do not require a 2FA verification through your webview. But for those who need to do that verification it will crash when tapping the Finish button on that page. Stacktrace of the crash is below. What could I be doing wrong? or is this and issue with a library that you guys uses?

```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.configure.init' on a null object reference
        at com.cardinalcommerce.a.setSpannableFactory.init(:2082)
        at com.cardinalcommerce.a.setPrivateImeOptions.Cardinal(:38564)
        at com.cardinalcommerce.a.setPrivateImeOptions$7.onClick(:389)
        at android.view.View.performClick(View.java:7201)
        at android.view.View.performClickInternal(View.java:7170)
        at android.view.View.access$3500(View.java:806)
        at android.view.View$PerformClick.run(View.java:27582)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by sshropshire** [comment]
Hi @Gimbergsson thanks for using the Braintree SDK for Android. Are you able to re-produce this with any of our [3D Secure test cards](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live/node#testing)? We can cross reference and attempt to reproduce on our side.

**Comment by Gimbergsson** [comment]
> Hi @Gimbergsson thanks for using the Braintree SDK for Android. Are you able to re-produce this with any of our [3D Secure test cards](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live/node#testing)? We can cross reference and attempt to reproduce on our side.

Hi, sorry I think this wasn't in Sandbox so it was in Production but I'll try to test those out in Sandbox.

**Comment by Gimbergsson** [comment]
@sshropshire I have now tested it and was able to reproduce it. I tested with the Visa card under "Successful Challenge Authentication", with card number 4000000000001091 and expiry date 01/25.

The only difference is that I couldn't enter a 2FA code so I just tapped verify, then it crashed with the same stacktrace.

**Comment by Gimbergsson** [comment]
@sshropshire I've tried same credentials in your demo app and it works fine there. But it's the demo project I've been following and I can't seems to find any difference with the way I implemented it. 🤔 

This is the `ThreeDSecureRequest` we use
```
val threeDSecureRequest = ThreeDSecureRequest().apply {
    amount = "1"
    email = user.email
    nonce = cardNonce.string
    versionRequested = ThreeDSecureRequest.VERSION_2
}
```
