### ISSUE TITLE
RuntimeException: Unable to start ThreeDSecureActivity due to NPE

### ISSUE THREAD

**Issue by karenethayer** [braintree/braintree_android#564]
### General information

* SDK/Library version: 4.10.1
* Environment: Production
* Android Version and Device: Android 12, 11, 9, 6.  94% Samsung (Galaxy S5, S10e, S8), 6% Huawei Y6 2019. 
* Braintree dependencies:
- com.braintreepayments.api:braintree:4.10.1
- com.braintreepayments.api:data-collector:4.10.1
- com.braintreepayments.api:three-d-secure:4.10.1

### Issue description

Production Crash, Steps to reproduce are unknown: 

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.snapfish.mobile/com.braintreepayments.api.ThreeDSecureActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.oe.d' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.oe.d' on a null object reference
       at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue(:21082)
       at com.braintreepayments.api.CardinalClient.continueLookup(CardinalClient.java:44)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreateInternal(ThreeDSecureActivity.java:39)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by sshropshire** [comment]
Hi @karenethayer thanks for using the Braintree SDK for Android. This appears to be a [duplicate](https://github.com/braintree/braintree_android/issues/470) issue with a 3rd-party library we use for 3DS authentication called Cardinal.

Our latest [4.12.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4120) version contains the most up-to-date version of Cardinal. Could you update to the latest version and report back [here](https://github.com/braintree/braintree_android/issues/470) if the issue still persists?

**Comment by xiaxiayige** [comment]
Android  12
SDK : 4.12.0  

'''
Non-fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ccc.aaa/com.braintreepayments.api.ThreeDSecureActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.s.d' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.s.d' on a null object reference
       at com.cardinalcommerce.cardinalmobilesdk.a.a(:60)
       at com.braintreepayments.api.e0.d(CardinalClient.java:4)
       at com.braintreepayments.api.ThreeDSecureActivity.s0(ThreeDSecureActivity.java:4)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:2)
       at android.app.Activity.performCreate(Activity.java:8057)
       at android.app.Activity.performCreate(Activity.java:8037)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
'''
