### ISSUE TITLE
java.lang.UnsupportedOperationException: This isn't a hierarchical URI

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#591]
### General information

* SDK/Library version:  4.15.0
* Environment: Sandbox
* Android Version and Device:  Any
* Compile SDK version:  33
* Target SDK version: 31

* Braintree dependencies: 
```
com.braintreepayments.api:card:4.15.0
com.braintreepayments.api:three-d-secure:4.15.0
```

### Issue description
Stacktrace of the crash is below. That crash I get from crashlytics report and don`t have steps
```
Fatal Exception: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
       at android.net.Uri.getQueryParameterNames(Uri.java:1616)
       at com.cardinalcommerce.a.setTextKeepState.getInstance(:6145)
       at com.cardinalcommerce.a.setTextKeepState$4.shouldOverrideUrlLoading(:104)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:46)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:339)
       at android.os.Looper.loopOnce(Looper.java:179)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by sshropshire** [comment]
Hi @auxDK thanks for using the Braintree SDK for Android. I've notified Cardinal, our 3rd Party MPI Provider of this issue, and we'll report back here with updates once we have more information.

**Comment by Kais-S** [comment]
Hello @sshropshire My team is facing the exact same random crash, any updates about this issue ?

**Comment by sshropshire** [comment]
Hi @Kais-S and @auxDK thank you for your patience. We were notified that this has been fixed in the latest version of Cardinal.

Can you update to the latest Braintree SDK version [4.20.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4200) and confirm?

**Comment by auxDK** [comment]
Hi @sshropshire, ok we have a new release in 2 weeks. I will be back later

**Comment by hollabaq86** [comment]
Closing this issue since we haven't heard from OP. If you encounter any further issues, please make a new issue or [contact Support](https://developer.paypal.com/braintree/help).
