### ISSUE TITLE
3DS / Cardinal SDK crash cca_continue

### ISSUE THREAD

**Issue by josephyanks** [braintree/braintree_android#601]
```
Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.configure.init' on a null object reference
       at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue(:21082)
       at com.braintreepayments.api.CardinalClient.continueLookup(CardinalClient.java:44)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreateInternal(ThreeDSecureActivity.java:39)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### General information

* SDK/Library version: 4.15.0
* Environment: Production 
* Android Version and Device: Samsung, OPPO, Android 9+
* Braintree dependencies: card, data-collector, google-pay, paypal, 3ds, all 4.15.0

```
        private const val braintreeVersion = "4.15.0"

        const val card = "com.braintreepayments.api:card:$braintreeVersion"
        const val dataCollector = "com.braintreepayments.api:data-collector:$braintreeVersion"
        const val googlePay = "com.braintreepayments.api:google-pay:$braintreeVersion"
        const val paypal = "com.braintreepayments.api:paypal:$braintreeVersion"
        const val threeDSecure = "com.braintreepayments.api:three-d-secure:$braintreeVersion"
        const val venmo = "com.braintreepayments.api:venmo:$braintreeVersion"
```

### Issue description

We are seeing this crash on app startup, but haven't been able to reproduce. This is a crash within the cardinal SDK that we don't have visibility into.

**Comment by josephyanks** [comment]
Oops, this is a duplicate of #592 so I'll post there going forward
