### ISSUE TITLE
3DS / Cardinal SDK crash on setEditableFactory.init

### ISSUE THREAD

**Issue by josephyanks** [braintree/braintree_android#602]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.configure.init' on a null object reference
       at com.cardinalcommerce.a.setEditableFactory.init(:2082)
       at com.cardinalcommerce.a.setOnEditorActionListener.onBackPressed(:29564)
       at android.app.Activity.onKeyUp(Activity.java:3169)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3374)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3452)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:124)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:142)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3090)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:578)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6067)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5922)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5428)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5394)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5553)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5402)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5610)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5428)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5394)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5402)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5375)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5428)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5394)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5586)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5755)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3409)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2856)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2847)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3386)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### General information

* SDK/Library version: 4.15.0
* Environment: Production 
* Android Version and Device: Samsung, OPPO, Android 9+
* Braintree dependencies: card, data-collector, google-pay, paypal, 3ds, all 4.15.0

```
        private const val braintreeVersion = "4.15.0"

        const val card = "com.braintreepayments.api:card:$braintreeVersion"
        const val dataCollector = "com.braintreepayments.api:data-collector:$braintreeVersion"
        const val googlePay = "com.braintreepayments.api:google-pay:$braintreeVersion"
        const val paypal = "com.braintreepayments.api:paypal:$braintreeVersion"
        const val threeDSecure = "com.braintreepayments.api:three-d-secure:$braintreeVersion"
        const val venmo = "com.braintreepayments.api:venmo:$braintreeVersion"
```

### Issue description

We are seeing this issue on our firebase crashlytics, but haven't been able to reproduce. This is a crash within the cardinal SDK that we don't have visibility into.

**Comment by scannillo** [comment]
👋 Hello! Thank you for bringing this to our attention. We have two similar issues already open.

You can try to replicate using the steps in https://github.com/braintree/braintree_android/issues/587. Otherwise, please follow along in https://github.com/braintree/braintree_android/issues/592.
