### ISSUE TITLE
Encryption failure in PayPal Native Checkout

### ISSUE THREAD

**Issue by smuldr** [braintree/braintree_android#614]
### General information

* SDK/Library version: PayPal Native Checkout 4.18.0
* Environment: Sandbox
* Android Version and Device: Emulator with Android 12 / API 31
* Braintree dependencies:
```
com.braintreepayments.api:braintree-core:4.18.0
com.braintreepayments.api:paypal-native-checkout:4.18.0
```

### Issue description

The PayPal Native checkout fails when the checkout callback URL is opened. It seems like there is something going wrong with the encryption? 
```
Exception in encrypting String
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
  at com.paypal.authcore.security.CryptoSecureKeyWrapperImpl.encryptDataUsingCipher(Unknown Source:0)
  at com.paypal.authcore.security.CryptoSecureKeyWrapperImpl.encryptStringUsingAES(Unknown Source:38)
  at com.paypal.authcore.util.cryptohelper.BaseCryptoHelper.encrypt(Unknown Source:14)
  at com.paypal.authcore.util.cryptohelper.CryptoHelperPKCS5.encrypt(Unknown Source:10)
  at com.paypal.authcore.util.BasePreferences.encryptAndAddToPreference(Unknown Source:40)
  at com.paypal.authcore.util.TokenState.persistRefreshToken(Unknown Source:2)
  at com.paypal.authcore.authentication.TokenService$a.onTokenRequestCompleted(Unknown Source:17)
  at com.paypal.openid.AuthorizationService$b.a(Unknown Source:95)
  at com.paypal.openid.AuthorizationService$b.onPostExecute(Unknown Source:2)
  at android.os.AsyncTask.finish(AsyncTask.java:771)
  at android.os.AsyncTask.access$900(AsyncTask.java:199)
  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

There are really two problems here:

1. The checkout fails because of some encryption error. This is bad but I guess it is also sort of expected behaviour when doing crypto on Android devices. 
2. Our `PayPalNativeCheckoutListener` listener never receives a callback when this happens, which leaves our app in a weird state. This is really the biggest problem if you ask me.

**Comment by sshropshire** [comment]
Hey @smuldr thanks for using the Braintree SDK for Android. Can you provide the steps needed to reproduce this error?

**Comment by smuldr** [comment]
I'm afraid that the best way to reproduce would be to find a device where the encryption master key is messed up.

**Comment by smuldr** [comment]
Looks like this is a duplicate of #619
