### ISSUE TITLE
App crashes on Braintree payment

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#624]
We have braintree integrated in our app, we updated target version of Android to 33 recently 

We are getting crashes eventually when we make payment on **Google Pixel 4a device with Android 13**

here is the crash log

Fatal Exception: java.lang.SecurityException: Settings key: <data_roaming> is only readable to apps with targetSdkVersion lower than or equal to: 32
       at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3081)
       at android.provider.Settings$Global.getStringForUser(Settings.java:15854)
       at android.provider.Settings$Global.getString(Settings.java:15837)
       at com.cardinalcommerce.shared.cs.f.k.<init>(:699)
       at com.cardinalcommerce.shared.cs.f.n.<init>(:5)
       at com.cardinalcommerce.shared.cs.f.g.a(:12)
       at com.cardinalcommerce.shared.cs.a.b.a(:2)
       at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(:123)
       at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(:24)
       at com.braintreepayments.api.ThreeDSecure.configureCardinal(ThreeDSecure.java:391)
       at com.braintreepayments.api.ThreeDSecure.access$100(ThreeDSecure.java:47)
       at com.braintreepayments.api.ThreeDSecure$4.onConfigurationFetched(ThreeDSecure.java:220)
       at com.braintreepayments.api.BraintreeFragment$14.run(BraintreeFragment.java:886)
       at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:819)
       at com.braintreepayments.api.BraintreeFragment$12.onConfigurationFetched(BraintreeFragment.java:846)
       at com.braintreepayments.api.ConfigurationManager$1.success(ConfigurationManager.java:59)
       at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
       
       Please help us

**Comment by sshropshire** [comment]
Hi @vakhileshwar please make sure your app targets the latest [4.20.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4200) version of the SDK to avoid this issue.

We added official support for Android 13 on versions greater than 4.18.0. Closing this for now. Feel free to re-open if you have additional integration issues.

**Comment by vakhileshwar** [comment]
Thank you @sshropshire
