### ISSUE TITLE
Creating BrainTree client out side of onCreate method  of activity crashes the app !

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#638]
java.lang.IllegalStateException: LifecycleOwner com.ui.activity.MainActivity@1d2ef20 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
                                                                                                    	at com.braintreepayments.api.ThreeDSecureLifecycleObserver.onStateChanged(ThreeDSecureLifecycleObserver.java:46)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
                                                                                                    	at com.braintreepayments.api.ThreeDSecureClient.addObserver(ThreeDSecureClient.java:93)
                                                                                                    	at com.braintreepayments.api.ThreeDSecureClient.<init>(ThreeDSecureClient.java:86)
                                                                                                    	at com.braintreepayments.api.ThreeDSecureClient.<init>(ThreeDSecureClient.java:53)

**Comment by sshropshire** [comment]
Hi @vakhileshwar thanks for using the Braintree SDK for Android. Unfortunately this is a side effect of the Activity Result API provided by the [Android team](https://developer.android.com/training/basics/intents/result). The `startActivityForResult` method was recently deprecated. For this reason, it is ideal for the SDK to be initialized within your Acitivty's `onCreate()` method.

Closing this for now. We are [actively soliciting feedback](https://github.com/braintree/braintree_android/discussions/496) for future versions of the SDK. If you wish, you can submit a feature request for your ideal API and we can collaborate on a solution that's both developer friendly and effective.
