### ISSUE TITLE
NullPointerException for ThreeDSecureResult in CardinalClient in 4.20.0

### ISSUE THREAD

**Issue by nadav-fima** [braintree/braintree_android#641]
**Integration Details (please complete the following information):**

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ajman.rider/com.braintreepayments.api.ThreeDSecureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.braintreepayments.api.ThreeDSecureLookup com.braintreepayments.api.ThreeDSecureResult.b()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.braintreepayments.api.ThreeDSecureLookup com.braintreepayments.api.ThreeDSecureResult.b()' on a null object reference
       at com.braintreepayments.api.CardinalClient.continueLookup(CardinalClient.java:41)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreateInternal(ThreeDSecureActivity.java:39)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:28)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

* SDK/Library version: 4.20.0
* Environment: Production
* Android Version and Device: Pixel 3a with Android 11
* Braintree dependencies:
```
    implementation 'com.braintreepayments.api:card:4.20.0'
    implementation 'com.braintreepayments.api:google-pay:4.20.0'
    implementation 'com.braintreepayments.api:paypal:4.20.0'
    implementation 'com.braintreepayments.api:local-payment:4.20.0'
    implementation 'com.braintreepayments.api:data-collector:4.20.0'

    implementation ('com.braintreepayments.api:three-d-secure:4.20.0') {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.braintreepayments.api:drop-in:6.4.0'
    implementation 'com.braintreepayments:encryption:2.1.0'
```
**Describe the bug**
We're not sure what the issue is, but we saw a couple crashes like it in production since upgrading from Braintree 3.17 to 4.20

**To Reproduce**
We do not know the steps to reproduce this. we haven't run into this.
We only see it in Crashlytics.

**Comment by sshropshire** [comment]
Hi @nadav-fima thanks for using the Braintree SDK for Android, we appreciate this feedback. I believe the best solution here may be for us to defensively guard against launching Cardinal in this scenario. We'll take note of this and put it in a future release.

We use `ThreeDSecureActivity` internally to forward control to Cardinal, our 3rd Party MPI for 3DS. Somehow this activity is being launched with no extras. I'm not exactly sure how this could occur, but it's possible the Android OS could be launching the activity on its own in some extreme edge case scenario.

**Comment by nadav-fima** [comment]
Yea, we thought that what it looked like as well.

**Comment by sshropshire** [comment]
For tracking: Ticket No. 2179

**Comment by sshropshire** [comment]
@nadav-fima this should be good now in version [4.23.1](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4231)!
