### ISSUE TITLE
[GooglePay] Non-fatal Exception: java.lang.VerifyError

### ISSUE THREAD

**Issue by xiaxiayige** [braintree/braintree_android#643]
**Integration Details (please complete the following information):**

* SDK/Library version: 4.20.0
* Environment: Production
* Android Version and Device: Android 11
* Braintree dependencies:
"com.braintreepayments.api": [
      "venmo:4.20.0",
      "braintree-core:4.20.0",
      "three-d-secure:4.20.0",
      "shared-utils:4.20.0",
      "paypal:4.20.0",
      "google-pay:4.20.0",
      "data-collector:4.20.0",
      "card:4.20.0",
      "browser-switch:2.3.1",
      "paypal-data-collector:4.20.0"
    ]

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

**Stacktrace**
```
Non-fatal Exception: java.lang.VerifyError: Verifier rejected class androidx.work.impl.OperationImpl: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult() failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult(): [0x2]  can't resolve returned type 'Unresolved Reference: com.google.common.util.concurrent.ListenableFuture' or 'Unresolved Reference: androidx.work.impl.utils.futures.SettableFuture' (declaration of 'androidx.work.impl.OperationImpl' appears in /data/app/~~_3kR6a3UMapQazZgQv3PIw==/com.hungrypanda.waimai-_131NBncS0eT6UGcw1OZGQ==/base.apk!classes3.dex)
       at androidx.work.impl.utils.EnqueueRunnable.<init>(EnqueueRunnable.java:79)
       at androidx.work.impl.WorkContinuationImpl.enqueue(WorkContinuationImpl.java:186)
       at androidx.work.impl.WorkManagerImpl.enqueueUniqueWork(WorkManagerImpl.java:409)
       at androidx.work.WorkManager.enqueueUniqueWork(WorkManager.java:351)
       at com.braintreepayments.api.AnalyticsClient.scheduleAnalyticsWrite(AnalyticsClient.java:92)
       at com.braintreepayments.api.AnalyticsClient.sendEvent(AnalyticsClient.java:77)
       at com.braintreepayments.api.AnalyticsClient.sendEvent(AnalyticsClient.java:69)
       at com.braintreepayments.api.BraintreeClient.sendAnalyticsEvent(BraintreeClient.java:231)
       at com.braintreepayments.api.BraintreeClient.access$000(BraintreeClient.java:17)
       at com.braintreepayments.api.BraintreeClient$2$1.onResult(BraintreeClient.java:221)
       at com.braintreepayments.api.BraintreeClient$1$1.onResult(BraintreeClient.java:188)
       at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:50)
       at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:183)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:210)
       at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:179)
       at com.braintreepayments.api.BraintreeClient$2.onAuthorizationResult(BraintreeClient.java:218)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:210)
       at com.braintreepayments.api.BraintreeClient.sendAnalyticsEvent(BraintreeClient.java:214)
       at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:249)
       at com.braintreepayments.api.GooglePayClient.requestPayment(GooglePayClient.java:228)
```

**Comment by sshropshire** [comment]
Hi @xiaxiayige thanks for using the Braintree SDK for Android. This appears to be an internal error with Jetpack WorkManager. Does this happen often and does it cause an app crash?

**Comment by sshropshire** [comment]
Hi @xiaxiayige is there any additional information available on this crash?

**Comment by xiaxiayige** [comment]
> Hi @xiaxiayige is there any additional information available on this crash?

thank you for your reply,
Yes, a crash occurred,
It may be due to our internal optimization, which forced us to specify the version of some libraries. Now there is no such problem, thank you
