### ISSUE TITLE
Drop-In UI crashes 

### ISSUE THREAD

**Issue by andhie** [braintree/braintree_android#67]
Following the code in https://developers.braintreepayments.com/guides/drop-in/android/v2

In app.gradle
```groovy
compile 'com.braintreepayments.api:braintree:2.1.0'
compile 'com.braintreepayments.api:drop-in:2.1.0'
```

starting Drop-In UI
```java
public void onBraintreeSubmit(View v) {
  PaymentRequest paymentRequest = new PaymentRequest()
      .clientToken(clientToken);
  startActivityForResult(paymentRequest.getIntent(this), REQUEST_CODE);
}
```

After the UI is launched, just click on the PayPal image/button. it will crash immediately

```java
java.lang.ArrayIndexOutOfBoundsException: too much data for RSA block
   at com.android.org.bouncycastle.jce.provider.JCERSACipher.engineDoFinal(JCERSACipher.java:457)
   at javax.crypto.Cipher.doFinal(Cipher.java:1111)
   at com.paypal.android.sdk.onetouch.core.cy.a(Unknown Source)
   at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.getBrowserSwitchUrl(Unknown Source)
   at com.paypal.android.sdk.onetouch.core.AuthorizationRequest.getRecipeToExecute(Unknown Source)
   at com.paypal.android.sdk.onetouch.core.PayPalOneTouchCore.getStartIntent(Unknown Source)
   at com.braintreepayments.api.PayPal$1.onConfigurationFetched(PayPal.java:128)
   at com.braintreepayments.api.BraintreeFragment$7.run(BraintreeFragment.java:409)
   at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:341)
   at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:401)
   at com.braintreepayments.api.PayPal.authorizeAccount(PayPal.java:105)
   at com.braintreepayments.api.PaymentButton.onClick(PaymentButton.java:194)
   at android.view.View.performClick(View.java:4084)
   at android.view.View$PerformClick.run(View.java:16966)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4745)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lkorth** [comment]
Thanks for letting us know about this @andhie.

This is actually an issue for any integration using PayPal, not just Drop-in. We'll take a look and get a fix out.

**Comment by JinCheng55555** [comment]
Dear, Ikorth
I want to know how to import project to android studio. I am a beginner in android development.
I am interested in your Drop-in UI . I want to make auto payment in android app. If you know about this, 
let me teach. 
Thank you for your attention.

**Comment by lkorth** [comment]
@JinCheng55555: there are lots of resources online that have tutorials on using Android Studio and our documentation also includes the [lines to add](https://developers.braintreepayments.com/start/hello-client/android/v2#android-sdk-setup) for the dependency.

Issues in this repo should be used for specific issues relating to the code in this repo. This issue is already about a specific crash in Drop-in and comments should only be made that pertain to this issue.

**Comment by cristianlucaci** [comment]
@lkorth can you please advise if this issue only affects version 2.1.0? Getting the same error myself.

**Comment by lkorth** [comment]
@cristianlucaci this crash is present in all 2.x versions.

**Comment by lkorth** [comment]
We have a fix for this issue and will be releasing it in the near future.

**Comment by cristianlucaci** [comment]
Hi @lkorth , 
any ETA for the fix? Thanks

**Comment by lkorth** [comment]
@cristianlucaci 2.1.1 was just released with this fix
