### ISSUE TITLE
app crashes after i got clientToken from server

### ISSUE THREAD

**Issue by patelanil2007** [braintree/braintree_android#68]
i got client token sucessfully from server

than i call payment request and app crashed

PaymentRequest paymentRequest = new PaymentRequest()
      .clientToken(clientToken);
  startActivityForResult(paymentRequest.getIntent(this), REQUEST_CODE);

//ERROR

FATAL EXCEPTION: main
                                                                      java.lang.VerifyError: com/braintreepayments/api/BraintreeFragment
                                                                          at com.braintreepayments.api.BraintreePaymentActivity.getBraintreeFragment(BraintreePaymentActivity.java:298)
                                                                          at com.braintreepayments.api.BraintreePaymentActivity.onCreate(BraintreePaymentActivity.java:105)
                                                                          at android.app.Activity.performCreate(Activity.java:5133)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by sdcoffey** [comment]
Hey @patelanil2007,

Thanks for pointing this out. `VerifyError` is thrown when the Android runtime detects an internal inconsistency with the class files provided. How are you integrating? Would you mind sharing your `build.gradle` file? 

Cheers,
Steve

**Comment by patelanil2007** [comment]
got solutions.  just update google play service and its working for me.

**Comment by momersaleem-sdsol** [comment]
Hello, 

I am getting the same error. I have already latest google play services installed on samsung galaxy s4 but issue still exists and it crashed everytime.
