### ISSUE TITLE
ClassNotFoundException  BraintreeBrowserSwitchActivity

### ISSUE THREAD

**Issue by xiaxiayige** [braintree/braintree_android#714]
### Braintree SDK Version

4.26.1

### Environment

Production

### Android Version & Device

Galaxy S22 Ultra   Android 13 

### Braintree dependencies

//  braintree = 4.26.1

api "com.braintreepayments.api:data-collector:$library.braintree"
 api "com.braintreepayments.api:card:$library.braintree"
api "com.braintreepayments.api:paypal:$library.braintree"
api "com.braintreepayments.api:three-d-secure:$library.braintree"
api "com.braintreepayments.api:venmo:$library.braintree"

api "com.braintreepayments.api:google-pay:$library.braintree"

### Describe the bug

`
Non-fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.xxx.xxx/com.braintreepayments.api.BraintreeBrowserSwitchActivity}: java.lang.ClassNotFoundException: Didn't find class "com.braintreepayments.api.BraintreeBrowserSwitchActivity" on path: DexPathList[[zip file "/data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/base.apk", zip file "/data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/split_config.arm64_v8a.apk", zip file "/data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/lib/arm64, /data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/base.apk!/lib/arm64-v8a, /data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~8N6H2FW_m8vLipiD4yyD2w==/com.xxx.xxx-bNiLiuaqF7OYyD4Drh_xGg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4051)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
`

### To reproduce

I don't know how to reproduce, 
the error comes from firebase crash log
but I didn't have this problem before using 4.20.0

### Expected behavior

crash

**Comment by sshropshire** [comment]
Hi @xiaxiayige thanks for using the BraintreeSDK for Android. I'm having trouble understanding this issue–we removed `BraintreeBrowserSwitchActivity` in `v4` of [our SDK](https://github.com/braintree/braintree_android/blob/65c6e0ae6de637491f08449e21e8922848878b0f/v4.9.0%2B_MIGRATION_GUIDE.md#browser-switch). Is it possible your project is also referencing `v3`?

**Comment by xiaxiayige** [comment]
> Hi @xiaxiayige thanks for using the BraintreeSDK for Android. I'm having trouble understanding this issue–we removed `BraintreeBrowserSwitchActivity` in `v4` of [our SDK](https://github.com/braintree/braintree_android/blob/65c6e0ae6de637491f08449e21e8922848878b0f/v4.9.0%2B_MIGRATION_GUIDE.md#browser-switch). Is it possible your project is also referencing `v3`?

Found the problem. It was caused by another payment SDK we introduced, and it has been processed, thanks for the reply
