### ISSUE TITLE
4.26.1 cardinalmobilesdk crash 

### ISSUE THREAD

**Issue by Jake-Jiang** [braintree/braintree_android#715]
### Braintree SDK Version

4.26.1 

### Environment

Production

### Braintree dependencies

                   braintreepaymentsVersion = 4.26.1 
                   braintree_card   : "com.braintreepayments.api:card:$braintreepaymentsVersion",
                    samsung_pay      : "com.braintreepayments.api:samsung-pay:$braintreepaymentsVersion",
                    paypal           : "com.braintreepayments.api:paypal:$braintreepaymentsVersion",
                    local_payment    : "com.braintreepayments.api:local-payment:$braintreepaymentsVersion",
                    union_pay        : "com.braintreepayments.api:union-pay:$braintreepaymentsVersion",
                    data_collector   : "com.braintreepayments.api:data-collector:$braintreepaymentsVersion",
                    three_d_secure   : "com.braintreepayments.api:three-d-secure:$braintreepaymentsVersion",
                    google_payment   : "com.braintreepayments.api:google-pay:$braintreepaymentsVersion",
                    american_express : "com.braintreepayments.api:american-express:$braintreepaymentsVersion",
                    card_form        : 'com.braintreepayments:card-form:5.4.0'

### Describe the bug

Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.configure.getInstance' on a null object reference
       at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue(:22082)
       at com.braintreepayments.api.CardinalClient.continueLookup(CardinalClient.java:44)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreateInternal(ThreeDSecureActivity.java:43)
       at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:31)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

### To reproduce

firebase user

### Expected behavior

no crash

**Comment by sshropshire** [comment]
Hi @Jake-Jiang do you know if this occurs for other versions of our SDK as well? We haven't received an update from Cardinal since version [4.18.0](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4180) of our SDK.

**Comment by sshropshire** [comment]
@Jake-Jiang we're following up with our 3rd Party MPI Cardinal.

**Comment by hollabaq86** [comment]
Update: We have #717 to try and catch these crashes in our SDK. We're also escalating with CardinalCommerce to update their SDK, but I can't provide an ETA on when a fix will be released on their side.

**Comment by hollabaq86** [comment]
@Jake-Jiang version 4.27.1 is out with these updates! Thanks for reporting this up to us
