### ISSUE TITLE
SecurityException in Cardinal Mobile SDK when targeting Android 14

### ISSUE THREAD

**Issue by ersen-lw** [braintree/braintree_android#762]
### Braintree SDK Version

4.27.0 (using drop-in 6.9.0

### Environment

Sandbox

### Android Version & Device

Android 14 Emulator (Sdk_gphone64_arm64) and Pixel 6 Pro

### Braintree dependencies

com.braintreepayments.api:drop-in:6.9.0

### Describe the bug

We are working on supporting Android 14. It has reached platform stability. 
When targeting Android 14 and running the app on a Android 14 device, making a test purchase throws the following crash. It appears the CardinalMobileSDK is accessing some setting value that is prohibited in SDK 34. 

```
Fatal Exception: java.lang.SecurityException: Settings key: <enabled_input_methods> is only readable to apps with targetSdkVersion lower than or equal to: 33
       at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3283)
       at android.provider.Settings$Secure.getStringForUser(Settings.java:6453)
       at android.provider.Settings$Secure.getIntForUser(Settings.java:6653)
       at android.provider.Settings$Secure.getInt(Settings.java:6647)
       at com.cardinalcommerce.a.setLastBaselineToBottomHeight.<init>(:151)
       at com.cardinalcommerce.a.setTextSize.<init>(:23)
       at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(:5055)
       at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:61)
       at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21)
       at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:162)
       at com.braintreepayments.api.BraintreeClient$getConfiguration$1$onAuthorizationResult$1.onResult(BraintreeClient.kt:179)
       at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.kt:30)
       at com.braintreepayments.api.BraintreeClient$getConfiguration$1.onAuthorizationResult(BraintreeClient.kt:175)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.kt:12)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.kt:197)
       at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.kt:172)
       at com.braintreepayments.api.ThreeDSecureClient.performVerification(ThreeDSecureClient.java:132)
       at com.braintreepayments.api.DropInInternalClient.performThreeDSecureVerification(DropInInternalClient.java:98)
       at com.braintreepayments.api.DropInActivity.lambda$onPaymentMethodNonceCreated$18(DropInActivity.java:523)
       at com.braintreepayments.api.DropInActivity.$r8$lambda$ATq97YBOn4IwsP42fj8T_HzvzZw(DropInActivity.java)
       at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda1.onResult(R8$$SyntheticClass)
       at com.braintreepayments.api.DropInInternalClient.lambda$shouldRequestThreeDSecureVerification$3(DropInInternalClient.java:132)
       at com.braintreepayments.api.DropInInternalClient.$r8$lambda$dXaMGzEbd9daqbWGQYjgQpM4Z40(DropInInternalClient.java)
       at com.braintreepayments.api.DropInInternalClient$$ExternalSyntheticLambda7.onResult(R8$$SyntheticClass)
       at com.braintreepayments.api.BraintreeClient$getConfiguration$1$onAuthorizationResult$1.onResult(BraintreeClient.kt:179)
       at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.kt:30)
       at com.braintreepayments.api.BraintreeClient$getConfiguration$1.onAuthorizationResult(BraintreeClient.kt:175)
       at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.kt:12)
       at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.kt:197)
       at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.kt:172)
       at com.braintreepayments.api.DropInInternalClient.shouldRequestThreeDSecureVerification(DropInInternalClient.java:124)
       at com.braintreepayments.api.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:521)
       at com.braintreepayments.api.DropInActivity.lambda$onCardDetailsSubmit$15(DropInActivity.java:516)
       at com.braintreepayments.api.DropInActivity.$r8$lambda$kxmLUMwtD0N1MPCTvutt-67q5Bc(DropInActivity.java)
       at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda9.onResult(R8$$SyntheticClass)
       at com.braintreepayments.api.CardClient.handleTokenizeResponse(CardClient.java:91)
       at com.braintreepayments.api.CardClient.access$100(CardClient.java:14)
       at com.braintreepayments.api.CardClient$1$1.onResult(CardClient.java:68)
       at com.braintreepayments.api.ApiClient$tokenizeGraphQL$1$1.onResult(ApiClient.kt:20)
       at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:123)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### To reproduce

Make a test purchase with 3D secure on a app that targets 34 (Android 14) observe the crash. 

### Expected behavior

Make a test purchase with 3D secure on a app that targets 34 (Android 14) should not crash.

**Comment by ersen-lw** [comment]
Hi @sshropshire any update on this ? It is holding back our compatibility branch and HealthConnect implementation

**Comment by sshropshire** [comment]
Hi @ersen-lw I don't have an update at the moment. We've reached out to Cardinal and they mentioned this would be a part of their next release, and it seems they are nearly complete with a new release–however they have not provided us with an official timeline. We'll provide new updates here when we receive them.

**Comment by ersen-lw** [comment]
Thanks @sshropshire

**Comment by sarahkoop** [comment]
The latest Cardinal SDK version supports Android 14 and has been updated in Braintree Android 4.38.1 - please upgrade to resolve this issue!
