### ISSUE TITLE
java.lang.NullPointerException - Attempt to read from field 'java.lang.String com.cardinalcommerce.a.init.d' on a null object reference

### ISSUE THREAD

**Issue by JeffYi2017** [braintree/braintree_android#778]
### Braintree SDK Version

4.36.0

### Environment

Production

### Android Version & Device

Xiaomi   Samsung  Oppo  Android 11/12/13

### Braintree dependencies

 api 'com.braintreepayments.api:paypal:4.36.0'
 api 'com.braintreepayments.api:data-collector:4.36.0'
 api 'com.braintreepayments.api:venmo:4.36.0'
api 'com.braintreepayments.api:three-d-secure:4.36.0'

### Describe the bug

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.init.d' on a null object reference
       at com.cardinalcommerce.a.setCompoundDrawableTintMode.init(SourceFile:2082)
       at com.cardinalcommerce.a.setTextSelectHandleRight.configure(SourceFile:38597)
       at com.cardinalcommerce.a.setTextSelectHandleRight$6.onClick(SourceFile:398)
       at android.view.View.performClick(View.java:7688)
       at android.view.View.performClickInternal(View.java:7661)
       at android.view.View.access$3600(View.java:837)
       at android.view.View$PerformClick.run(View.java:29028)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

### To reproduce

3ds verification

### Expected behavior

no crash

**Comment by JeffYi2017** [comment]
Another crash like this

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.cardinalcommerce.a.setMax.s1(com.cardinalcommerce.a.setDividerDrawable)' on a null object reference
       at com.cardinalcommerce.a.setCompoundDrawableTintMode.configure(SourceFile:117)
       at com.cardinalcommerce.a.values.cca_continue(SourceFile:81)
       at com.cardinalcommerce.a.setInterpolator$2.run(SourceFile:110)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by sarahkoop** [comment]
Hi @JeffYi2017 - Can you provide steps to reproduce the error, a screen recording of the error if possible, and a code snipped of your ThreeDSecure integration? We will open a ticket about this with Cardinal, but they will need more information to debug.

**Comment by Jake-Jiang** [comment]
I also get many crash report from our customer.

**Comment by sshropshire** [comment]
Hi @Jake-Jiang can you provide any additional information here? Are you using the same SDK version as @JeffYi2017?

**Comment by sarahkoop** [comment]
Closing this due to inactivity. The latest version of the braintree_android SDK (currently `4.38.2`) contains an updated version of the Cardinal SDK. Please upgrade and feel free to re-open if you are still experiencing this issue!
