### ISSUE TITLE
NPE because of race condition in BraintreePaymentActivity

### ISSUE THREAD

**Issue by sachins** [braintree/braintree_android#83]
I start the BraintreePaymentActivity with following code from MyAppActivity:
```java
PaymentRequest request = new PaymentRequest()
                        .clientToken(token)
                        .submitButtonText("Save");
                startActivityForResult(request.getIntent(this), 1);
```

The payment activity UI looks fine when I let it load. 

But if I hit back button while the BraintreePaymentActivity is still loading (showing the loading spinner with lock), in a few seconds (about 5 seconds) I see following crash:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.example, PID: 9166
                                                                  android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class fragment
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                      at android.view.ViewStub.inflate(ViewStub.java:259)
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.inflateOrFind(BraintreePaymentActivity.java:401)
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.show(BraintreePaymentActivity.java:420)
                                                                      at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:271)
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:248)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class fragment
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.ViewStub.inflate(ViewStub.java:259) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.inflateOrFind(BraintreePaymentActivity.java:401) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.show(BraintreePaymentActivity.java:420) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:271) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:248) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.FragmentHostCallback.getContext()' on a null object reference
                                                                      at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2200)
                                                                      at android.app.FragmentController.onCreateView(FragmentController.java:98)
                                                                      at android.app.Activity.onCreateView(Activity.java:5559)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.ViewStub.inflate(ViewStub.java:259) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.inflateOrFind(BraintreePaymentActivity.java:401) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.show(BraintreePaymentActivity.java:420) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:271) 
                                                                      at com.braintreepayments.api.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:248) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I can reproduce this crash very easily on version 2.2.0.

**Comment by sachins** [comment]
I can reproduce this with version 2.2.0 as well.

**Comment by lkorth** [comment]
@sachins It appears that this is being caused by a network request returning a response to the Activity after it has finished. This is a little surprising since in the [`BraintreeFragment`](https://github.com/braintree/braintree_android/blob/master/BraintreeApi/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L191) we unregister the activity's callbacks in `onPause`. 

I am unable to reproduce this on a variety of devices, emulators and networks and doesn't appear to be an issue for me so I have no way of testing the fix for this. Are you able to reproduce this on different devices, emulators or networks? As it stands we can check to see if the Activity has finished when handling callbacks or we can prevent users from pressing the back button when it is initially loading.

**Comment by sachins** [comment]
I was definitely able to reproduce this on 2.1.0, but it seems like I am not able to reproduce it on 2.2.0 anymore. Closing this issue. Will reopen if I come across it again.

**Comment by lkorth** [comment]
That makes more sense, in 2.1.1 [a change](https://github.com/braintree/braintree_android/commit/e40de2f36bdf0396a798ea210ab948124d1df85c) was made to fix a similar issue.
