### ISSUE TITLE
Paypal native checkout can't work

### ISSUE THREAD

**Issue by ningkanggithub** [braintree/braintree_android#843]
### Braintree SDK Version

4.39.0

### Environment

Both

### Android Version & Device

All

### Braintree dependencies

com.braintreepayments.api:paypal-native-checkout:4.39.0

### Describe the bug

@org.json.JSONException: Unterminated string at 57 [character 0 line 2]
                                                                                                    	at q00.f.e(Unknown Source:17)
                                                                                                    	at q00.f.d(Unknown Source:364)
                                                                                                    	at q00.b.<init>(SourceFile:19)
                                                                                                    	at q00.b.<init>(SourceFile:40)
                                                                                                    	at com.paypal.pyplcheckout.data.api.calls.CancelUrlApi.createService(Unknown Source:33)
                                                                                                    	at com.paypal.pyplcheckout.data.api.BaseApi.enqueueRequest(Unknown Source:44)
                                                                                                    	at com.paypal.pyplcheckout.data.repositories.Repository.fetchCancelURL(Unknown Source:12)
                                                                                                    	at com.paypal.checkout.PayPalCheckout$handleLaunchOrder$1.invoke(SourceFile:3)
                                                                                                    	at com.paypal.checkout.PayPalCheckout$handleLaunchOrder$1.invoke(SourceFile:1)
                                                                                                    	at com.paypal.checkout.createorder.CreateOrderActions$setBillingAgreementId$1.invokeSuspend(Unknown Source:120)
                                                                                                    	at jx.a.resumeWith(Unknown Source:8)
                                                                                                    	at dy.s0.run(Unknown Source:111)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:966)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9923)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [d2{Cancelling}@e1e66bd, Dispatchers.Main]

### To reproduce

Upgrade 
gradle-8.0-bin.zip
gradle plugin : "8.1.3"

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

and then : 
Paypal native checkout can't work

### Expected behavior

normal work

**Comment by sarahkoop** [comment]
Hi @ningkanggithub - Could you provide a few more details about this error please? Can you please provide code snippets of your integration, and a video showing when in the flow this error is occurring, or steps to reproduce? Also, is this error occurring on initial integration or upgrade?

**Comment by sarahkoop** [comment]
Closing this due to inactivity - if you are still experiencing this issue, please feel free to re-open with the requested information!
