### ISSUE TITLE
ConcurrentModificationException crash

### ISSUE THREAD

**Issue by RadoslawHardyl** [braintree/braintree_android#87]
Lately we find out that, we have a lot of crashes related with Braintree SDK. Below you can find a crash report:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
    at com.devicecollector.CollectorProcess.checkIfDone(SourceFile:197)
    at com.devicecollector.CollectorProcess.doInBackground(SourceFile:126)
    at com.devicecollector.CollectorProcess.doInBackground(SourceFile:34)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 3 
```

As you can see it is related with braintree device collector class.
I found on github very similar issue to this one: https://github.com/braintree/braintree_android/issues/53
the reason is the same, even the class in which crash occur.
We already are using SDKversion 1.7.5, like @lkorth  suggested.
I also have checked new newest version of SDK and implementation is the same as in 1.7.5.

Most of crashes comes from devices with android 6.0(Marshmallow), but there is a few from older devices.

Can you take a look on this issue?

**Comment by lkorth** [comment]
@RadoslawHardyl: thanks for the report. I'll check with our fraud partner for an update to the library to fix this crash.

**Comment by lkorth** [comment]
I've updated the library with a fix. It will be available in the next release of 1.x and 2.x.

**Comment by RadoslawHardyl** [comment]
@lkorth  thanks for your hard work! I will check the new version after the release.
