### ISSUE TITLE
BraintreeHttpClient.setBaseUrl(java.lang.String) on a null object reference

### ISSUE THREAD

**Issue by TheGreat0004** [braintree/braintree_android#89]
I am using braintree api to get add card in app for payments. It works fines and sometimes crashes randomly,

This is my stacktrace,

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.braintreepayments.api.internal.HttpClient com.braintreepayments.api.internal.BraintreeHttpClient.setBaseUrl(java.lang.String)' on a null object reference
                                                              at com.braintreepayments.api.BraintreeFragment.setConfiguration(BraintreeFragment.java:488)
                                                              at com.braintreepayments.api.BraintreeFragment$5.onConfigurationFetched(BraintreeFragment.java:415)
                                                              at com.braintreepayments.api.ConfigurationManager.getConfiguration(ConfigurationManager.java:46)
                                                              at com.braintreepayments.api.BraintreeFragment.fetchConfiguration(BraintreeFragment.java:412)
                                                              at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:458)
                                                              at com.braintreepayments.api.TokenizationClient.tokenize(TokenizationClient.java:72)
                                                              at com.braintreepayments.api.Card.tokenize(Card.java:29)
                                                              at cl.tk.ui.activities.sub_activity.AddPayment$UIThreadHandler$1.run(AddPayment.java:364)
                                                              at java.lang.Thread.run(Thread.java:818)
```

with following url of stackoverflow question,

http://stackoverflow.com/questions/36502781/braintreehttpclient-setbaseurljava-lang-string-on-a-null-object-reference/36503357?noredirect=1#comment60614184_36503357

**Comment by brunobar79** [comment]
+1

**Comment by lkorth** [comment]
Please try version 2.2.4, released today. This appears to be a race condition with fragments not being attached to the host activity before other code, in this case tokenizing a credit card, is run.

**Comment by lkorth** [comment]
@TheGreat0004 have you been able to reproduce the issue with 2.2.4? If not I'll close the issue.
